### ISSUE TITLE
这个怎么自定义长按事件？

### ISSUE THREAD

**Issue by 200895045** [indulgeIn/YBImageBrowser#1]
fuctionDataArray置为空，toolBar 和 functionBar都隐藏掉
之后可以自定义长按事件吗？或者长按弹出的ActionSheet可以自定义吗？

**Comment by indulgeIn** [comment]
2.0 重做版本已更新  支持自定义长按

**Comment by ThisFriend** [comment]
> 2.0 重做版本已更新 支持自定义长按

请问一下，现在的自定义长按要怎么处理？没有看到暴露的接口，在项目介绍中也没有提及

**Comment by indulgeIn** [comment]
@property (nonatomic, weak) id<YBImageBrowserDelegate> delegate; 这个代理有个方法

**Comment by ThisFriend** [comment]
respondsToLongPress  , 看到了。
