### ISSUE TITLE
占位图片的问题

### ISSUE THREAD

**Issue by huhangatzz** [indulgeIn/YBImageBrowser#10]
网络比较慢或者图片比较大的时候加载是页面时黑色的,就一个进度视图显示,没有占位图片,感觉体验不好,如果作者能添加在加载的时候有占位图显示就比较不错了.体验会更好些

**Comment by indulgeIn** [comment]
阅读以下readme或者API。是有占位图的配置的

**Comment by indulgeIn** [comment]
2.0 重做版本已更新  若设置了sourceObject不需设置缩略图

**Comment by iamlay** [comment]
您好，3.0版本的占位图设置有吗？看了API和readme都没发现。

**Comment by indulgeIn** [comment]
@iamlay 有呀，就在 YBIBImageData 类

**Comment by iamlay** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    嗯嗯，已找到，谢谢！！！
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1187074543
                            
                    
                        
                            
                                    1187074543@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2019年09月26日 11:34，波儿菜<notifications@github.com> 写道： 


@iamlay 有呀，就在 YBIBImageData 类



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
