### ISSUE TITLE
如何自定义Browser高度?

### ISSUE THREAD

**Issue by liangcha** [indulgeIn/YBImageBrowser#103]
我尝试add进了一个Controlle里作为子View, 但这个Browser内部是写死了Browser高度，在外部的设置没达到想要的效果。

**Comment by indulgeIn** [comment]
浏览器大小是满屏的 不支持修改

**Comment by indulgeIn** [comment]
3.0-beta 已支持添加到其它父视图使用，可参考 DEMO 中的示例
