### ISSUE TITLE
高清图片过多，快速滑动时会奔溃

### ISSUE THREAD

**Issue by michaelxxw** [indulgeIn/YBImageBrowser#105]
场景：总共有50多张图片，每张400K+，当快速滑动时，到40几张时，会闪退，且没有捕捉到异常，推断是内存不够，被强制回收了，或者是野指针，录了一个视频：[https://d.pr/v/C2LAOt](https://d.pr/v/C2LAOt)

**Comment by indulgeIn** [comment]
建议使用代理方式配置数据源，数据源及时释放能降低内存峰值。可以多看看readme有解释的😊

**Comment by michaelxxw** [comment]
我用的就是代理模式~~

**Comment by michaelxxw** [comment]
好滴，我这边再试一下

**Comment by michaelxxw** [comment]
经过尝试，关闭上述几个属性后，暂时没有发现闪退问题了

**Comment by indulgeIn** [comment]
shouldDecodeAsynchronously 异步绘制功能应该不用关。
