### ISSUE TITLE
为什么要依赖YYImage

### ISSUE THREAD

**Issue by SPStore** [indulgeIn/YBImageBrowser#108]
假如人家项目里不需要YYImage，用你这个框架还必须导入YYImage

**Comment by indulgeIn** [comment]
因为考虑到实现Gif，支持webP、APNG等的时间成本。这只是个UI组件，我也没有很多时间去重复造轮子。如果你们项目里对代码把控很严，那参考我这个库做一个符合自己项目的轮子是个比较好的方式。
