### ISSUE TITLE
加载图片的时候下拉会崩溃

### ISSUE THREAD

**Issue by CoderSimonWong** [indulgeIn/YBImageBrowser#11]
当图片还在加载0%到100%的时候，这个时候手势往下拉，就会崩溃。

Thread 1: signal SIGABRT

**Comment by CoderSimonWong** [comment]
。。。

**Comment by indulgeIn** [comment]
@CoderSimonWong 抱歉，遗漏了 issues 邮件。问题已解决，代码已上传，pods得今晚晚些时候才能更新。
