### ISSUE TITLE
横屏显示不全的问题

### ISSUE THREAD

**Issue by LiJian-China** [indulgeIn/YBImageBrowser#110]
iPad横屏，点击图片预览，图片显示不全

**Comment by indulgeIn** [comment]
需要截图才能定位问题

**Comment by LiJian-China** [comment]
好的。  一张竖屏的正常截图，一张横屏的问题截图，请查看
<img width="720" alt="a0" src="https://user-images.githubusercontent.com/7576100/52759876-7ded6800-3048-11e9-82a0-a56abe03f9a6.png">
<img width="1050" alt="a1" src="https://user-images.githubusercontent.com/7576100/52759884-82b21c00-3048-11e9-88f8-44b7e4c21866.png">

**Comment by indulgeIn** [comment]
YBImageBrowseCellData 下的 verticalfillType 和 horizontalfillType 可以改变填充方式，你可以选择完整显示。
