### ISSUE TITLE
提两个小问题

### ISSUE THREAD

**Issue by XQBoy** [indulgeIn/YBImageBrowser#111]
1.在 YBIBPhotoAlbumManager 这个类中引用到了 ALAssetsLibrary 去保存图片，但在 iOS 9 之后就需要换成Photos framework，所以可以加上版本判断；
2.将 YBImageBrowser 整个加进项目后，分别在 YBImageBrowseCell 和 YBVideoBrowseCell 会报警告： Assigning to 'YBImageBrowseCellData *' from incompatible type '__strong id<YBImageBrowserCellDataProtocol> _Nonnull'；
希望以上问题能得到处理，谢谢

**Comment by indulgeIn** [comment]
保存图片这个版本暂时能用就行了，后面重构考虑去做处理。警告貌似没有啊？
