### ISSUE TITLE
EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by wangjunjie1004** [indulgeIn/YBImageBrowser#113]
当我浏览一些图片的时候，会出现野指针，尤其是某些大图，概率会高一些。
debug时，发现生成压缩图这个方法会进入好几次，第一次和最后一次算出来的size差别特别大，最后一次算出来的size很大，导致内存增长，所以崩溃了。崩溃时栈顶在viewDidAppeare.
<img width="996" alt="18de4d3b-b64c-4c33-8225-a241e72924cc" src="https://user-images.githubusercontent.com/39542866/53385672-28a34600-39ba-11e9-82b5-16b43f9c4356.png">

**Comment by wangjunjie1004** [comment]
请问看了吗

**Comment by indulgeIn** [comment]
新版已修复内存溢出问题

**Comment by wangjunjie1004** [comment]
> 新版已修复内存溢出问题

我使用的就是新版，依然存在

**Comment by indulgeIn** [comment]
新版是这样算的：CGSize size = [self getSizeOfCompressing]; 这个方法不会返回很大的size，你看看具体的版本号呢

**Comment by wangjunjie1004** [comment]
> 新版是这样算的：CGSize size = [self getSizeOfCompressing]; 这个方法不会返回很大的size，你看看具体的版本号呢

版本确实是最新的，但是我继续debug，发现好像是我外面传图片的问题，谢谢回复
