### ISSUE TITLE
关于保存相册toast显示问题

### ISSUE THREAD

**Issue by woshicainiaohahaha** [indulgeIn/YBImageBrowser#115]
我发现有时候会不显示成功或者失败的toast，然后我打印控制台发现：po YBIBGetNormalWindow()
<UIWindow: 0x107521110; frame = (0 0; 375 667); hidden = YES; gestureRecognizers = <NSArray: 0x2801e9b60>; layer = <UIWindowLayer: 0x280f90b60>>
也就是说normalwindow有可能是隐藏的；
我修改代码如下，您看合适吗？
UIWindow *YBIBGetNormalWindow(void) {
    UIWindow *window = [[UIApplication sharedApplication] keyWindow];
    if (window.hidden) {
        NSArray *windows = [[UIApplication sharedApplication] windows];
        for(UIWindow *temp in windows) {
            if (!temp.hidden) {
                window = temp; break;
            }
        }
    }
    return window;
}

**Comment by indulgeIn** [comment]
新版已经改了，始终用keyWindow作为toast载体

**Comment by woshicainiaohahaha** [comment]
好的 已更新 谢谢
