### ISSUE TITLE
CocoaPods pod install 安装文件太大

### ISSUE THREAD

**Issue by jerryhu** [indulgeIn/YBImageBrowser#123]
CocoaPods安装时，需要clone整个项目。

整个项目文件, 大概190M!!

https://api.github.com/repos/indulgeIn/YBImageBrowser
> "size": 195413

**Comment by indulgeIn** [comment]
是这样的么？请问这个路径怎么看

**Comment by jerryhu** [comment]
路径应该就是在配置文件设置的
https://github.com/indulgeIn/YBImageBrowser/blob/master/YBImageBrowser.podspec

https://stackoverflow.com/a/25658514

**Comment by indulgeIn** [comment]
那clone的应该只是 YBImageBrowser 文件夹下内容

**Comment by jerryhu** [comment]
pod 'YBImageBrowser', :git => 'https://gitee.com/mirrors/YBImageBrowser.git'

运行pod install --verbose
```
$ /usr/bin/git clone https://gitee.com/mirrors/YBImageBrowser.git
     /var/folders/9p/pb31vx_n19b8yghw24z6n20h0000gn/T/d20190322-1380-1ysk1el
     --template= --single-branch --depth 1
     Cloning into '/var/folders/9p/pb31vx_n19b8yghw24z6n20h0000gn/T/d20190322-1380-1ysk1el'...
```

然后发现项目的 **所有文件** 都下载到了临时文件夹 /var/folders/9p/pb31vx_n19b8yghw24z6n20h0000gn/T/d20190322-1380-1ysk1el

**Comment by indulgeIn** [comment]
嗯。2.1.5版本减少了release包体积

**Comment by jerryhu** [comment]
删除了Demo项目文件后，CocoaPods安装就超快了
https://github.com/jerryhu/YBImageBrowser

`pod 'YBImageBrowser', :git => 'https://github.com/jerryhu/YBImageBrowser.git'`

建议将Demo项目单独建一个repository

**Comment by indulgeIn** [comment]
只要保证 release 包体积够小就行了吧，和主分支大小没关系吧
