### ISSUE TITLE
你好 滑动的时候有些卡段  下面是我的代码, 版本为最新版本

### ISSUE THREAD

**Issue by HYongLL** [indulgeIn/YBImageBrowser#124]
这是加载的Document路劲下的图片文件, 滑动的时候有些卡段.
>   YBImageBrowseCellData *data = [YBImageBrowseCellData new];
>                     data.imageBlock = ^YBImage *{ 
>                    return      [YBImage imageWithContentsOfFile:m.imagePath]; };
>                     data.sourceObject = [self sourceObjAtIdx:idx];
>                     [_imageURLArray addObject:data];

**Comment by HYongLL** [comment]
是这个方法的原因吗 imageWithContentsOfFile

**Comment by indulgeIn** [comment]
会在异步读取，不会卡

**Comment by HYongLL** [comment]
但是滑动的过程中 确实有一些卡段.  你要是方便的话 可以加下我qq 给你看一段录屏你就能发现了  QQ: 1285022791

**Comment by indulgeIn** [comment]
就发这里吧，读取会在异步，就算是卡顿也不是这个部分。

**Comment by HYongLL** [comment]
是高清图片太多的问题, 根据以前的问题 解决了.
