### ISSUE TITLE
打开本地沙盒视频文件，提示图片无效

### ISSUE THREAD

**Issue by liujieyuu** [indulgeIn/YBImageBrowser#125]
打开本地沙盒视频文件，提示图片无效文件路径：file:///var/mobile/Containers/Data/Application/2A5E714C-C640-46B6-93B7-FC368B6BA130/Documents/waterVideo2.mp4

**Comment by indulgeIn** [comment]
视频是用 YBVideoBrowseCellData 配置哟

**Comment by liujieyuu** [comment]
@indulgeIn 对啊，是跟着你的demo写的
