### ISSUE TITLE
建议在.podspec文件中添加依赖库的版本号

### ISSUE THREAD

**Issue by MrBugDou** [indulgeIn/YBImageBrowser#127]
SDWebImage已经更新至5.0，目前项目的代码不支持5.0会报错，后续建议在.podspec文件中修改依赖为如下代码（指定依赖库的版本号），每次更新时根据情况修改依赖库的版本号
s.dependency 'YYImage', '~> 1.0.4'
s.dependency 'SDWebImage', '~> 4.4.6'

**Comment by fanbaoyuanbees360** [comment]
同需求，SDWebImage跟新到了5.0了，但是YBImageBrowser使用5.0的SD会报错，我现在只能使用4.4.6版本的SD，希望大佬能关注下这个issure

**Comment by indulgeIn** [comment]
但是直接指定依赖版本会增加与其他库依赖冲突的几率。可能最简单的处理方式是更新依赖SD5.0的版本，空了我看下

**Comment by MrBugDou** [comment]
你更新依赖SD5.0的版本自然最好，不过你依然可以增加依赖
s.dependency 'SDWebImage', '~> 5.0.0'
至于和其他第三方库的冲突如果一直维持最新的某种成都上还是有问题，举个栗子：某第三方库依赖于SD4.4.6，你的下一版依赖SD5.0，那么这个冲突就不可避免了

**Comment by indulgeIn** [comment]
对呀，综合考虑来看，三方依赖不指定版本能兼容更多的场景。
这些问题确实有些头大，除了去掉依赖没有完美的解决方案。

**Comment by MrBugDou** [comment]
可是不加依赖就是默认最新呀😂，但是加上依赖起码可以抱着比如你停更1年甚至更久，单独一个pod还能使用，如果不加依赖的话停更比较久直接pod就会出现不兼容的问题，使用者需要倒推回去找兼容的依赖版本库

**Comment by indulgeIn** [comment]
但是规范的操作是需要在 podfile 指定每一个库的版本，比如 pod 'SDWebImage', '~> x.x.x' ，而不应该依赖三方库的依赖来导入。
主要是有很多库都依赖 SD，它们很多指定了版本，若我这个也指定，出现冲突几率太大了，之前有很多人提了这个问题，才去掉依赖版本的。不指定版本至少不会pod冲突，所以你完全可以在podfile指定SD版本来暂时规避这个问题。

**Comment by MrBugDou** [comment]
'~> x.x.x' 的含义是最低需要支持这个版本，加与不加不会影响你说的冲突问题，因为按常理来讲，高版本的代码应该向下兼容低版本的代码，此处指定版本也只是指定最低支持这个版本

**Comment by indulgeIn** [comment]
嗯是这样 但是SD就是没做好兼容问题

**Comment by indulgeIn** [comment]
2.1.7 已支持最新 SD
