### ISSUE TITLE
低内存设备 OOM 问题

### ISSUE THREAD

**Issue by mahaiyang** [indulgeIn/YBImageBrowser#132]
用代理的方式 ，YBImageBrowseCellData 没有设置 sourceObject 情况下，浏览30张 2.5M的在线图片时。快速的滑动会崩溃。如果 YBImageBrowseCellData 设置了 sourceObject 的话正常滑几下就崩溃了

**Comment by indulgeIn** [comment]
针对代理方式：确保外部没有持有图片浏览器的数据源，尝试关闭预加载功能，尝试将缓存数量调低

**Comment by mahaiyang** [comment]
YBImageBrowser *browser = [YBImageBrowser new];
    browser.dataCacheCountLimit=1;
    browser.dataSource=self;
    browser.shouldPreload=NO;
  
 外部没有持有图片浏览器的数据源。关闭了预加载功能和降低缓存数量后慢慢滑动是不会闪退了。但是当快速滑动的时候还是会崩溃。即使9张图片的时候快速滑动也会崩溃

**Comment by mahaiyang** [comment]
上面的问题都是在iphone6上出现的。在6s及以上机型不会有问题

**Comment by indulgeIn** [comment]
那还有一步可以降低内存，直接关闭异步绘制。看一下有没有暴露的接口 我忘记了

**Comment by indulgeIn** [comment]
YBImageBrowseCellData.shouldDecodeAsynchronously = NO; 
关闭异步绘制，能降低内存峰值

**Comment by indulgeIn** [comment]
2.2.0 更新了。
自动降低了内存消耗，看看能不能直接解决问题。

**Comment by lxb0706** [comment]
快速滑动的内存飙升会被系统kill掉的的问题解决了？这个不局限iphon6啊。。

**Comment by mahaiyang** [comment]
> 快速滑动的内存飙升会被系统kill掉的的问题解决了？这个不局限iphon6啊。。

我们app暂时没有发现崩溃的情况了。就是按照上面的方法设置了
browser.shouldPreload=NO;
browser.dataCacheCountLimit=1;
YBImageBrowseCellData.shouldDecodeAsynchronously = NO;
。好像新版本作者已经解决了，我目前还没有试

**Comment by indulgeIn** [comment]
内部是判断物理内存小于 1.0+G 就会降低性能以及减小内存占用，这些逻辑是可以通过 API 控制的，内部只是提前做了一下控制。2.2.0+ 版本或者 3.0-beta 都支持。

其实如果高清图太多，目前也没有什么好的办法来降低 CPU 和内存压力，因为你始终需要让用户看到清晰的局部或者全景，那使用高清图来绘制就是必要的。
可以提前压缩一下过大的图片然后赋值数据源，但是裁剪的图片就不是最清晰的效果了。

理论上客户端不应该有大量的高清图片来展示，这本身就不太合理，你可以看看 QQ、微信都不能搞大图的。

**Comment by mahaiyang** [comment]
> 内部是判断物理内存小于 1.0+G 就会降低性能以及减小内存占用，这些逻辑是可以通过 API 控制的，内部只是提前做了一下控制。2.2.0+ 版本或者 3.0-beta 都支持。
> 
> 其实如果高清图太多，目前也没有什么好的办法来降低 CPU 和内存压力，因为你始终需要让用户看到清晰的局部或者全景，那使用高清图来压缩或裁剪就是必要的，虽然比直接解码轻量，但还是会消耗可观的内存。
> 可以提前压缩一下过大的图片然后赋值数据源，但是裁剪的图片就不是最清晰的效果了。
> 
> 理论上客户端不应该有大量的高清图片来展示，这本身就不太合理，你可以看看 QQ、微信都不能搞大图的。
我们的app界面显示是用的缩略图，点击查看图片的时候才去加载大图。这样内存压力应该会小一点。如果你们app的图片是上传到阿里云的话。界面显示的时候可以用阿里云的缩略图方式访问，图片url地址后面加“?x-oss-process=image/resize,m_fill,h_高度,w_宽度”就可以访问缩略图了。后台不用做处理。

**Comment by mahaiyang** [comment]
> 内部是判断物理内存小于 1.0+G 就会降低性能以及减小内存占用，这些逻辑是可以通过 API 控制的，内部只是提前做了一下控制。2.2.0+ 版本或者 3.0-beta 都支持。
> 
> 其实如果高清图太多，目前也没有什么好的办法来降低 CPU 和内存压力，因为你始终需要让用户看到清晰的局部或者全景，那使用高清图来压缩或裁剪就是必要的，虽然比直接解码轻量，但还是会消耗可观的内存。
> 可以提前压缩一下过大的图片然后赋值数据源，但是裁剪的图片就不是最清晰的效果了。
> 
> 理论上客户端不应该有大量的高清图片来展示，这本身就不太合理，你可以看看 QQ、微信都不能搞大图的。

我们的app界面显示是用的缩略图，点击查看图片的时候才去加载大图。这样内存压力应该会小一点。如果你们app的图片是上传到阿里云的话。界面显示的时候可以用阿里云的缩略图方式访问，图片url地址后面加“?x-oss-process=image/resize,m_fill,h_高度,w_宽度”就可以访问缩略图了。后台不用做处理。

**Comment by lxb0706** [comment]
我这边是加载的相册原图，快速滑动加载导致的内存暴增； 我试了下3.0的版本。。加载相册原图，内存管理会比2.x版本的好一些，但一直加载的话，还是会有内存问题。。。

**Comment by indulgeIn** [comment]
@lxb0706 快速滑动内存不会暴增，是 CPU 会高速运转，因为要不停的解码。。

**Comment by lxb0706** [comment]
> @lxb0706 快速滑动内存不会暴增，是 CPU 会高速运转，因为要不停的解码。。

内存也会暴增，instruments上看内存确实飚的厉害

**Comment by indulgeIn** [comment]
@lxb0706 嗯对，快速滑动不光 CPU 高速运转，异步绘制上下文导致内存也会涨，不过这个问题目前无法避免，在 README 中说明了减少硬件消耗的方法。
