### ISSUE TITLE
浏览url图片，显示图片无效，图片地址如下

### ISSUE THREAD

**Issue by yanmingLiu** [indulgeIn/YBImageBrowser#134]
https:\/\/img40.huju168.com\/Fgio6WEp8MXAUGnioO5ciTjnX_UB?e=1556003676&token=bUt0LWmEEuUBIo6w5hcJChCcErfOhIsdFqE3fYam:GOBoqB3mSzMX7c82ECNrBjtbgnU=

**Comment by indulgeIn** [comment]
没有拓展名

**Comment by yanmingLiu** [comment]
> 没有拓展名

我觉得不是扩展名的问题，像下面的2个连接，第一个可以浏览（上传时公开密钥），第二个就不行（上传时密钥传输，返回的url是解密后的地址）；2个连接浏览器都正常访问；

https://img40.huju168.com/Fgio6WEp8MXAUGnioO5ciTjnX_UB?e=1556003676&token=bUt0LWmEEuUBIo6w5hcJChCcErfOhIsdFqE3fYam:GOBoqB3mSzMX7c82ECNrBjtbgnU=

https://img25.huju168.com\/FjqcdyYMsQ4944kTpOEb7dSDjdnL?e=1556507766&token=bUt0LWmEEuUBIo6w5hcJChCcErfOhIsdFqE3fYam:DfkHggg42rQU7cIwxw7fPrEFemg=

**Comment by indulgeIn** [comment]
该组件也是用的 SD 下载图片，我在 Demo 中添加了第二个能正常展示啊

**Comment by yanmingLiu** [comment]
> 该组件也是用的 SD 下载图片，我在 Demo 中添加了第二个能正常展示啊

我pod下来的版本是(2.1.7)，我发现没有这个类YBImageBrowserModel ， 而是用的YBImageBrowseCellData， 我跟新一下试试

**Comment by indulgeIn** [comment]
哦，那个估计是很早的版本了

**Comment by yanmingLiu** [comment]
> 哦，那个估计是很早的版本了

1.0.8  这个demo 我试了是ok的，我2.1.7这个不行；你试的demo是2.2的吗？

**Comment by indulgeIn** [comment]
Demo是最新的版本
