### ISSUE TITLE
指定版本

### ISSUE THREAD

**Issue by 948769029** [indulgeIn/YBImageBrowser#137]
兄弟你这写的完全不行啊,sdwebimage  yyimage 还指定版本 那你怎么去让所有人用你这框架 搞笑呢吧

**Comment by indulgeIn** [comment]
你完全可以提出一种可行性的方案，如果觉得写得垃圾可以不用，去看其它开源库吧。

**Comment by 948769029** [comment]
哦 提建议也不行哈

**Comment by indulgeIn** [comment]
你这像是提建议么
