### ISSUE TITLE
整个项目只支持竖屏，这个图片预览要支持横竖屏，该怎么设置？试了都没什么效果

### ISSUE THREAD

**Issue by FCF5646448** [indulgeIn/YBImageBrowser#138]
整个项目只支持竖屏，这个图片预览要支持横竖屏，该怎么设置？试了都没什么效果

**Comment by FCF5646448** [comment]
类似微信的图片预览横竖屏效果

**Comment by indulgeIn** [comment]
图片浏览器内部是支持旋转的，它只是一个UIViewController，旋转相关设置是通用的，搜索一下吧

**Comment by indulgeIn** [comment]
可以看一下技术原理 https://www.jianshu.com/p/bffdb9f0036c 第七点

**Comment by indulgeIn** [comment]
3.0-beta 已支持主动旋转，直接设置属性就行

**Comment by vitanie** [comment]
> 3.0-beta 已支持主动旋转，直接设置属性就行
能否实现直接横屏，不管设备是否横竖屏
