### ISSUE TITLE
作者你好 ，以后会加上类似微信查看原图功能吗 ？因为目前很多场景都需要查看原图这个功能

### ISSUE THREAD

**Issue by LZJProject** [indulgeIn/YBImageBrowser#139]

**Comment by indulgeIn** [comment]
这个自定义 toolBar ，点击自定义按钮后更新数据源，最后刷新UI：YBImageBrowser 的 reloadData 方法

**Comment by LZJProject** [comment]
<img width="1168" alt="WechatIMG3" src="https://user-images.githubusercontent.com/35026471/57289959-0121d580-70ef-11e9-94d7-98cefa88bdf7.png">

**Comment by LZJProject** [comment]
<img width="1168" alt="WechatIMG3" src="https://user-images.githubusercontent.com/35026471/57289983-14cd3c00-70ef-11e9-9e00-f9ac641c6ec7.png">
作者您好，我已经按照你的思路自定义了toolbar  并且通过通知将数据源传递到了我的vc，进行了替换之后，用browser reload。并没有实现刷新图片的功能， 还请您解答下

**Comment by indulgeIn** [comment]
cellData 是做了缓存的，所以直接更换一个 cellData 就行了。

**Comment by indulgeIn** [comment]
3.0-beta Demo 中做了一个查看原图的实现示例
