### ISSUE TITLE
这个能添加一个删除的接口吗

### ISSUE THREAD

**Issue by FranLucky** [indulgeIn/YBImageBrowser#140]

**Comment by indulgeIn** [comment]
数据源有数组方式和代理方式提供，也就是说本身数据源就是用户自己维护的，所以 YBImageBrowser 只提供了一个 reloadData 来刷新界面。

**Comment by FranLucky** [comment]
reload能满足需求，希望能开放出collection的删除indexpaths的接口，避免不必要的操作

**Comment by indulgeIn** [comment]
这种接口无法对代理方式的数据源进行操作，并且会对外部业务进行侵入，并不安全
