### ISSUE TITLE
用下库好难，最终sdwebimage用的4.4.6,本库用的2.1.5算是编译过了，有还没集成成功的老铁可以一试

### ISSUE THREAD

**Issue by kzq5** [indulgeIn/YBImageBrowser#143]

**Comment by indulgeIn** [comment]
是啊只要依赖了三方，潜在的冲突不可避免，应用库几乎做不到向下兼容。

**Comment by kzq5** [comment]
> 是啊只要依赖了三方，潜在的冲突不可避免，应用库几乎做不到向下兼容。

不过还是感谢作者的库，写的挺好

**Comment by indulgeIn** [comment]
真说不上好，凑合用吧 😂

**Comment by indulgeIn** [comment]
最新版已经对 SDWebImage 向上模糊依赖，并能支持不依赖 SDWebImage，详情见 README 相关描述。
