### ISSUE TITLE
请教作者关于横屏显示的问题

### ISSUE THREAD

**Issue by jiejieshow1** [indulgeIn/YBImageBrowser#146]
在混合案例中,我设置YBImageBrowseCellData的horizontalfillType = YBImageBrowseFillTypeCompletely时,图片可以满屏显示,但是在显示demo中第9张超长图片时,希望是以YBImageBrowseFillTypeFullWidth显示,请问可以实现吗?

**Comment by indulgeIn** [comment]
可以呀，可以每个data单独配置 在看一下接口吧
