### ISSUE TITLE
这个是怎么了，下不来

### ISSUE THREAD

**Issue by jiazufei** [indulgeIn/YBImageBrowser#148]
[!] Error installing YBImageBrowser
[!] /usr/local/bin/git clone https://github.com/indulgeIn/YBImageBrowser.git /var/folders/9c/k9vpkx_j1gb36pnq0cgrd6d40000gn/T/d20190514-7682-1ega41l --template= --single-branch --depth 1 --branch 2.2.0

Cloning into '/var/folders/9c/k9vpkx_j1gb36pnq0cgrd6d40000gn/T/d20190514-7682-1ega41l'...
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by jiazufei** [comment]
pod 这个库非常慢，不清楚什么原因

**Comment by amovexu** [comment]
我也碰到这个问题了

**Comment by singular7310** [comment]
确实慢

**Comment by indulgeIn** [comment]
3.0-beta DMEO 瘦身到 6m 了
