### ISSUE TITLE
长视频会识别成图片，并且不播放

### ISSUE THREAD

**Issue by jiazufei** [indulgeIn/YBImageBrowser#150]
// Type 1 : 网络视频 / Network video
                YBVideoBrowseCellData *data = [YBVideoBrowseCellData new];
                data.url = [NSURL URLWithString:@"http://files-storage.oss-cn-beijing.aliyuncs.com/2a718f2d34f5377d5f5e16f259eecbd0.mp4"];
  data.sourceObject = [self sourceObjAtIdx:idx];
                [browserDataArr addObject:data];

**Comment by indulgeIn** [comment]
这个链接会直接下载呀

**Comment by jiazufei** [comment]
会走图片那个if
