### ISSUE TITLE
sourceobject传入UIWiew，打开动画效果有问题

### ISSUE THREAD

**Issue by guangzai630** [indulgeIn/YBImageBrowser#153]
enter_configAnimateImageView方法里
`self.animateImageView.layer.contents = view.layer;`
改成
`self.animateImageView.layer.contents = view.layer.contents;`
如果是bug点，希望尽快更新，项目在用。

**Comment by indulgeIn** [comment]
2.2.1 更新了，传 UIView 时会直接截图，可能会导致动画不自然，所以不建议传 UIView，最好是 UIImageView。
