### ISSUE TITLE
左上角数字和关闭按钮重叠问题

### ISSUE THREAD

**Issue by ApesTalk** [indulgeIn/YBImageBrowser#157]
预览的数据中有图片和视频，当滑到视频页播放过程中用手指左右滑动，滑动到半屏的时候视频暂停了，然后再滑回来，数字和关闭按钮重叠了。
![bug](https://user-images.githubusercontent.com/5499434/59182719-f69aa600-8b9c-11e9-85e6-289597bb452e.png)

**Comment by indulgeIn** [comment]
3.0-beta 修复了这个问题
