### ISSUE TITLE
进度条可以隐藏吗

### ISSUE THREAD

**Issue by aa335418265** [indulgeIn/YBImageBrowser#158]
进度条可以隐藏吗

**Comment by indulgeIn** [comment]
目前版本是不行的。

**Comment by aa335418265** [comment]
求更新支持 ！
还有图片预览的左上角的索引“4/7” 能不能支持 在底部用...代替

**Comment by indulgeIn** [comment]
视频模块不好拓展了，本身写得不太好，可以直接里面去改。
那些通用的工具栏都可以自定义的，看一下 readme 和接口吧，有个 toolbars 属性。

这个库有些设计缺陷，后续我准备深度重构。

**Comment by aa335418265** [comment]
好的，谢谢大神！------------------ 原始邮件 ------------------
发件人: "杨波"<notifications@github.com>
发送时间: 2019年6月13日(星期四) 晚上6:35
收件人: "indulgeIn/YBImageBrowser"<YBImageBrowser@noreply.github.com>;
抄送: "aa335418265"<335418265@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [indulgeIn/YBImageBrowser] 进度条可以隐藏吗 (#158)



视频模块不好拓展了，本身写得不太好，可以直接里面去改。
 那些通用的工具栏都可以自定义的，看一下 readme 和接口吧，有个 toolbars 属性。
 
这个库有些设计缺陷，后续我准备深度重构。
 
&mdash;

**Comment by indulgeIn** [comment]
3.0-beta 优化了loading的显示逻辑，DEMO中提供了定制ToolView是简易方法。
