### ISSUE TITLE
调用YBImageBrowser之后，打开UICollectionView页面闪退

### ISSUE THREAD

**Issue by alexiiio** [indulgeIn/YBImageBrowser#159]
其他页面有UICollectionView，调用YBImageBrowser展示图片方法之前可以正常显示，在调用YBImageBrowser之后，再打开有UICollectionView的页面就会闪退，排查发现UICollectionView的numberOfItemsInSection:方法走的是YBImageBrowser的，然后会因为找不到yb_dataSource方法而闪退。 报错信息如下：

-[QDDropDownItem yb_dataSource]: unrecognized selector sent to instance 0x7fe03f471870
2019-06-11 17:35:06.289780+0800 Amusing[32140:1795167] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[QDDropDownItem yb_dataSource]: unrecognized selector sent to instance 0x7fe03f471870'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010a1a86fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010ce11ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010a1c6ab4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   UIKitCore                           0x0000000117cedc3d -[UIResponder doesNotRecognizeSelector:] + 287
	4   CoreFoundation                      0x000000010a1ad443 ___forwarding___ + 1443
	5   CoreFoundation                      0x000000010a1af238 _CF_forwarding_prep_0 + 120
	6   Amusing                             0x00000001092c3617 -[YBImageBrowserView collectionView:numberOfItemsInSection:] + 71
	7   UIKitCore                           0x0000000117573e09 -[UICollectionViewData _updateItemCounts] + 409
	8   UIKitCore                           0x00000001175769a0 -[UICollectionViewData isIndexPathValid:validateItemCounts:] + 51
	9   UIKitCore                           0x0000000117576a64 -[UICollectionViewData validatedGlobalIndexForItemAtIndexPath:] + 41
	10  UIKitCore                           0x000000011754a01d -[UICollectionView _cellForItemAtIndexPath:includePrefetchedCells:] + 126
	11  UIKitCore                           0x000000011753432d -[UICollectionView _selectItemAtIndexPath:animated:scrollPosition:notifyDelegate:] + 471
	12  UIKitCore                           0x00000001175344b2 -[UICollectionView selectItemAtIndexPath:animated:scrollPosition:] + 128
...

请大佬看看...

**Comment by indulgeIn** [comment]
这个应该不是这个组件的问题吧，内部并没有做runtime或分类来hook什么，应该去排查 QDDropDownItem 为什么会调用到组件里面的方法。

**Comment by alexiiio** [comment]
抱歉，经过一些检查，发现是另一个库 `TABAnimated` 导致的，那个库hook了UICollectionView的代理方法，还不清楚是哪里搞混乱的，但是注释掉Method-Swizzle方法就好了。那我把这个issue关闭了

**Comment by indulgeIn** [comment]
👌
