### ISSUE TITLE
一个数组越界问题的崩溃

### ISSUE THREAD

**Issue by ChuGuangFu** [indulgeIn/YBImageBrowser#161]
`UIViewController *YBIBGetTopController(void) {
    UIViewController *topController = nil;
    UIWindow *window = YBIBGetNormalWindow();
    UIView *frontView = [[window subviews] objectAtIndex:0];
    id nextResponder = [frontView nextResponder];
    if ([nextResponder isKindOfClass:UIViewController.class]) {
        topController = nextResponder;
    } else {
        topController = window.rootViewController;
        while (topController.presentedViewController) {
            topController = topController.presentedViewController;
        }
    }
    return topController;
}`

这段代码中
UIView *frontView = [[window subviews] objectAtIndex:0];
偶尔会崩溃，原因是数组越界了

**Comment by indulgeIn** [comment]
新版已修复。
