### ISSUE TITLE
能否支持传入URLRequest来实现图片加载

### ISSUE THREAD

**Issue by pinksunHenry** [indulgeIn/YBImageBrowser#165]
在我的使用场景中，图片无法通过url直接获取，必须增加设置token作为httpHeader。实际上，我觉得这个场景还是有很多的。或者能否提供一个解决方案去处理呢。
还有就是看您的好像跟系统的效果比较像，如果能尽快支持livePhoto就更好了。

**Comment by indulgeIn** [comment]
3.0-beta 支持修改 Request

**Comment by pinksunHenry** [comment]
谢谢您的回复，我现在用你那个异步的block处理了一下，等你的正式版出来之后我再更新，谢谢您！

发自冯丹阳
