### ISSUE TITLE
同时（时间间隔很短）点击两张图片，崩溃

### ISSUE THREAD

**Issue by ZhouTengFei** [indulgeIn/YBImageBrowser#168]
九宫格图片每张都添加手势，然后显示，当快速的点击来那个张图片时，崩溃#import "YBIBUtilities.h"
UIViewController *topController = nil;
    UIWindow *window = YBIBGetNormalWindow();
    UIView *frontView = [[window subviews] objectAtIndex:0];
请问，该如何避免？谢谢

**Comment by indulgeIn** [comment]
最新版本应该没问题了

**Comment by ZhouTengFei** [comment]
2.1.5版本的，昨天刚install的

**Comment by indulgeIn** [comment]
最新是2.2.x了
