### ISSUE TITLE
查看长图左右晃动

### ISSUE THREAD

**Issue by wuzhenli** [indulgeIn/YBImageBrowser#17]
在 ImageBrowserCell 里，如果设置 scrollView.alwaysBounceHorizontal =  YES， 查看长图的时候图片在 horizontal 方向会超出屏幕，将这个属性设置为 NO 可以吗？

**Comment by indulgeIn** [comment]
@wuzhenli 实验了一下超长图，是有点问题，我更改了是否需要异步裁剪的逻辑。并且你说的这个属性我改成了NO，跟业务逻辑应该是没有影响的

**Comment by wuzhenli** [comment]
在 cell 的 setCancelDragImageViewAnimation:(BOOL)cancelDragImageViewAnimation  方法里 self.scrollView.alwaysBounceHorizontal = !cancelDragImageViewAnimation; 这行也去掉吧!

**Comment by indulgeIn** [comment]
2.0 重做版本已更新
