### ISSUE TITLE
3.x版本 自定义工具视图 中调用self.yb_currentPage() 报错

### ISSUE THREAD

**Issue by laoji988** [indulgeIn/YBImageBrowser#174]
如题，在demo中试过 也crash 报错为 unrecognized selector sent to instance 0x280f01400'

**Comment by laoji988** [comment]
self.yb_totalPage(),也报错

**Comment by indulgeIn** [comment]
是不是没关联属性？

**Comment by laoji988** [comment]
>  是不是没关联属性？

关联过了。self.yb_currentOrientation()都没问题。 只有获取页数的时候会报错。我想要的是获取当前图片index,现在只能通过- (void)yb_offsetXChanged:(CGFloat)offsetX; 来获取了，麻烦作者大大看一下，谢谢！

**Comment by indulgeIn** [comment]
那应该是调用得太早了，浏览器都没准备好数据。在 `yb_containerViewIsReadied:`方法之后再去调用吧，表示容器准备好了（也包括数据）。

**Comment by laoji988** [comment]
> 那应该是调用得太早了，浏览器都没准备好数据。在 `yb_containerViewIsReadied:`方法之后再去调用吧，表示容器准备好了（也包括数据）。

- (void)yb_containerViewIsReadied {
    [self.yb_containerView addSubview:self.viewOriginButton];
    CGSize size = self.yb_containerSize(self.yb_currentOrientation());
    self.viewOriginButton.center = CGPointMake(size.width / 2.0, size.height - 80);
    NSInteger currentIndex = self.yb_currentPage();
    NSLog(@"%ld", currentIndex);
}


我在这个方法中调用 依然报错，

**Comment by indulgeIn** [comment]
错误日志？

**Comment by laoji988** [comment]
2019-07-23 16:59:35.492900+0800 YBImageBrowserDemo[26804:1657830] -[TestToolViewHandler yb_currentPage]: unrecognized selector sent to instance 0x6000031f3690
2019-07-23 16:59:35.499154+0800 YBImageBrowserDemo[26804:1657830] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[TestToolViewHandler yb_currentPage]: unrecognized selector sent to instance 0x6000031f3690'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010fecf6fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001112f3ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010feedab4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010fed41a1 ___forwarding___ + 769
	4   CoreFoundation                      0x000000010fed6238 _CF_forwarding_prep_0 + 120
	5   YBImageBrowserDemo                  0x000000010f9ed65b -[TestToolViewHandler yb_containerViewIsReadied] + 507
	6   YBImageBrowserDemo                  0x000000010f9b9a62 -[YBImageBrowser buildToolView] + 706
	7   YBImageBrowserDemo                  0x000000010f9b9716 -[YBImageBrowser build] + 742
	8   YBImageBrowserDemo                  0x000000010f9baf1b __43-[YBImageBrowser showToView:containerSize:]_block_invoke + 43
	9   YBImageBrowserDemo                  0x000000010f9b69af __113-[YBIBAnimatedTransition yb_showTransitioningWithContainer:startView:startImage:endFrame:orientation:completion:]_block_invoke.39 + 47
	10  UIKitCore                           0x000000011c474f3b -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:] + 847
	11  UIKitCore                           0x000000011c4488ff -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 343
	12  UIKitCore                           0x000000011c448f21 -[UIViewAnimationState animationDidStop:finished:] + 293
	13  QuartzCore                          0x0000000110a62de7 _ZN2CA5Layer23run_animation_callbacksEPv + 321
	14  libdispatch.dylib                   0x0000000112e0adb5 _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x0000000112e18080 _dispatch_main_queue_callback_4CF + 1540
	16  CoreFoundation                      0x000000010fe368a9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	17  CoreFoundation                      0x000000010fe30f56 __CFRunLoopRun + 2310
	18  CoreFoundation                      0x000000010fe30302 CFRunLoopRunSpecific + 626
	19  GraphicsServices                    0x00000001183b12fe GSEventRunModal + 65
	20  UIKitCore                           0x000000011bfb3ba2 UIApplicationMain + 140
	21  YBImageBrowserDemo                  0x000000010f9b9050 main + 112
	22  libdyld.dylib                       0x0000000112e7f541 start + 1
	23  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by laoji988** [comment]
> 错误日志？

2019-07-23 16:59:35.492900+0800 YBImageBrowserDemo[26804:1657830] -[TestToolViewHandler yb_currentPage]: unrecognized selector sent to instance 0x6000031f3690
2019-07-23 16:59:35.499154+0800 YBImageBrowserDemo[26804:1657830] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[TestToolViewHandler yb_currentPage]: unrecognized selector sent to instance 0x6000031f3690'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010fecf6fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001112f3ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010feedab4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010fed41a1 ___forwarding___ + 769
	4   CoreFoundation                      0x000000010fed6238 _CF_forwarding_prep_0 + 120
	5   YBImageBrowserDemo                  0x000000010f9ed65b -[TestToolViewHandler yb_containerViewIsReadied] + 507
	6   YBImageBrowserDemo                  0x000000010f9b9a62 -[YBImageBrowser buildToolView] + 706
	7   YBImageBrowserDemo                  0x000000010f9b9716 -[YBImageBrowser build] + 742
	8   YBImageBrowserDemo                  0x000000010f9baf1b __43-[YBImageBrowser showToView:containerSize:]_block_invoke + 43
	9   YBImageBrowserDemo                  0x000000010f9b69af __113-[YBIBAnimatedTransition yb_showTransitioningWithContainer:startView:startImage:endFrame:orientation:completion:]_block_invoke.39 + 47
	10  UIKitCore                           0x000000011c474f3b -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:] + 847
	11  UIKitCore                           0x000000011c4488ff -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 343
	12  UIKitCore                           0x000000011c448f21 -[UIViewAnimationState animationDidStop:finished:] + 293
	13  QuartzCore                          0x0000000110a62de7 _ZN2CA5Layer23run_animation_callbacksEPv + 321
	14  libdispatch.dylib                   0x0000000112e0adb5 _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x0000000112e18080 _dispatch_main_queue_callback_4CF + 1540
	16  CoreFoundation                      0x000000010fe368a9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	17  CoreFoundation                      0x000000010fe30f56 __CFRunLoopRun + 2310
	18  CoreFoundation                      0x000000010fe30302 CFRunLoopRunSpecific + 626
	19  GraphicsServices                    0x00000001183b12fe GSEventRunModal + 65
	20  UIKitCore                           0x000000011bfb3ba2 UIApplicationMain + 140
	21  YBImageBrowserDemo                  0x000000010f9b9050 main + 112
	22  libdyld.dylib                       0x0000000112e7f541 start + 1
	23  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by indulgeIn** [comment]
老哥，就是没写 `@synthesize yb_currentPage = _yb_currentPage;` 这句代码吧？😂

**Comment by laoji988** [comment]
> 老哥，就是没写 `@synthesize yb_currentPage = _yb_currentPage;` 这句代码吧？😂

我去。 我的锅。耽误您时间了。 不好意思。
