### ISSUE TITLE
yb_totalPage返回值不正确

### ISSUE THREAD

**Issue by Goyaya** [indulgeIn/YBImageBrowser#175]
设置数据源的断点情况
<img width="979" alt="image" src="https://user-images.githubusercontent.com/13333348/61786068-8d66ad80-ae3f-11e9-9430-b37f6215c289.png">

通过`yb_totalPage`获取值的情况
<img width="972" alt="image" src="https://user-images.githubusercontent.com/13333348/61786178-b9822e80-ae3f-11e9-9e42-9218a7e7ac5f.png">

这里的数量 `-1` ？和索引搞混了吧😂
<img width="669" alt="image" src="https://user-images.githubusercontent.com/13333348/61786924-44aff400-ae41-11e9-9131-e64a786b19c1.png">

最后，感谢您的开源贡献！

**Comment by indulgeIn** [comment]
已修复
