### ISSUE TITLE
直接隐藏 YBImageBrowser 视图出现 UI 异常

### ISSUE THREAD

**Issue by zhaojinjie** [indulgeIn/YBImageBrowser#176]
有很多跳转场景需要先隐藏图片浏览器，建议暴露出来，我记得2x版本是暴露出来的。

**Comment by indulgeIn** [comment]
YBImageBrowser 本身就是一个 UIView 直接隐藏就行了

**Comment by zhaojinjie** [comment]
不说什么，1.动画没了；2.点击的图片会变成空白。亲身体验还没之前的2x 好用

**Comment by indulgeIn** [comment]
可以查看demo用法 你说的情况可能是使用有误

**Comment by indulgeIn** [comment]
如果确实有BUG请具体说明一下

**Comment by zhaojinjie** [comment]
![Uploading Snip20190729_1.png…]()

**Comment by zhaojinjie** [comment]
![Snip20190729_1](https://user-images.githubusercontent.com/20727429/62031632-6bdc3c00-b21a-11e9-9b3d-6a478110d826.png)
![WechatIMG1](https://user-images.githubusercontent.com/20727429/62031645-772f6780-b21a-11e9-814f-295a6abb7956.jpeg)
 第一张图片是在你的自定义cell那个类型中添加了一个action,点击它隐藏图片浏览器,然后跳转controller，再返回就出现图2的情况。如果使用hide方法，就不会出现这种情况，我只能先放弃pod了。

**Comment by indulgeIn** [comment]
目前可以先将 autoHideProjectiveView 置为 NO 取消自动隐藏映射视图的效果

**Comment by zhaojinjie** [comment]
算了，放弃pod了，使用YBIBImageData初始化图片，actionSheet自动加上保存到相册，我又不想自定义，将YBIBImageData里面的yb_saveToPhotoAlbum注释了完事。

**Comment by zhaojinjie** [comment]
就算你将 autoHideProjectiveView 置为 NO后，还得调整windowLevel，要不状态栏还是隐藏的

**Comment by indulgeIn** [comment]
那就把 shouldHideStatusBar 也置为 NO。之前确实没有考虑到这种情况。

**Comment by zhaojinjie** [comment]
等你更新吧

**Comment by leisong1125** [comment]
我也是遇到这个类试的问题，也是需要这样的场景，要隐藏YBImageBrowser ，然后push

**Comment by leisong1125** [comment]
3.0的性能上确实比2.0 强很多，能升级到3.0 还是建议用3.0，我是用pod ，目前只能修改pod，把隐藏方法暴露
