### ISSUE TITLE
点击图片的时候只想显隐工具栏

### ISSUE THREAD

**Issue by jiutianhuanpei** [indulgeIn/YBImageBrowser#179]
就是我自定义一个工具栏，功能比较多比如下载图片、视频，查看原图等等一大堆，我想在查看图片的时候它们是隐藏的，点击一下图片来切换它们的显隐，只在上下滑动图片的时候隐去 browser ,这个应该怎么做呢，现在点击图片就隐去browser 了

**Comment by indulgeIn** [comment]
YBIBImageData 和 YBIBVideoData 都有一个 singleTouchBlock 属性
