### ISSUE TITLE
频繁 让状态栏隐藏 显示，导致状态栏不见了 页面卡住了

### ISSUE THREAD

**Issue by leisong1125** [indulgeIn/YBImageBrowser#180]
在浏览图片的时候，频繁的拖动图片，让状态栏显示和隐藏 之间 切换，然后屏幕会闪一下，回到页面上状态栏消失，同时 项目里用的路由 也导致失效, 多次重试 几乎是必现

**Comment by indulgeIn** [comment]
设备版本、repo版本？你的问题还需要具体描述一下。

**Comment by leisong1125** [comment]
目前所有设备上都存在这个问题，版本是2.0 ,目前 我已经升级到了最新的3.0 ,问题得到了解决，不得不说3.0 比2.0 是强大不少，但是好像也舍弃了不少，例如手动隐藏视图

**Comment by indulgeIn** [comment]
隐藏这个接口已经加入TODO
