### ISSUE TITLE
YBIBCopywriter 获取语言类型 BUG

### ISSUE THREAD

**Issue by zhifenx** [indulgeIn/YBImageBrowser#181]
你好 YBIBCopywriter 这个类没被初始化 运行了你的demo是有初始化的 但是获取的系统语言不够准确 不是只有“zh-Hans-CN”代表中文系统

**Comment by zhifenx** [comment]
我们的使用场景：首先我们不是九宫格式的图片展示，我们是用一个collection view 承载image view，也就是一屏只显示一张图片，可以左右滑动查看图片，当点击图片查看详情时就使用到了您的框架，此时有两个问题：
1、当打开一张横图时会有一个从大到小的动画，时间很短，但是很突兀。
2、假设我打开的是第一张图片，当我滑动到第二张图片时，此时我下滑关闭详情浏览时，图片会飞向第一张图的位置，但是此时collection view的第一个cell 已经滑到了屏幕外，所以目前我只能用browser.defaultAnimatedTransition.hideType = YBIBTransitionTypeNone;方式来避免这个尴尬的问题。我有尝试- (void)yb_imageBrowser:(YBImageBrowser *)imageBrowser pageChanged:(NSInteger)page data:(id<YBIBDataProtocol>)data回调里更改imageBrowser的currentPage，但是会崩到- (void)setHiddenProjectiveView:(id)hiddenProjectiveView这个方法。   我看了源码，currentPage会根据图片的滑动去改变，但是似乎对这种方式不起作用。是不是这个库只试用九宫格和新开UIVIewController展示图片的方式？

**Comment by indulgeIn** [comment]
第一个问题那个就是系统的UIView动画，效果看起来其实还好；第二个问题可能是给数据模型赋值映射视图时有误，出场的终点取决于这个映射视图。

**Comment by indulgeIn** [comment]
系统语言这个简体中文还有其它表示？

**Comment by JanWirt** [comment]
> 系统语言这个简体中文还有其它表示？

系统语言与地区里面，上面有个iPhone语言，下面有个地区，我语言是中文，地区是美国，工具栏就是英文。你试试根据地区来判断的？

**Comment by zhifenx** [comment]
我的iPhone X是目前是中午系统，打印出来语言是“zh-Hans-US”并不是源码里的“zh-Hans-CN”，所以这样判断中文系统是不严谨的。

**Comment by indulgeIn** [comment]
内部判断是有误的，只取 zh-Hans 部分就行，目前可以手动设置一下。
