### ISSUE TITLE
模拟器直接崩溃到该位置，请看下是什么问题？

### ISSUE THREAD

**Issue by cheng77** [indulgeIn/YBImageBrowser#182]
dyld: Symbol not found: _OBJC_CLASS_$_YBIBImageData
  Referenced from: /Users/ning/Library/Developer/CoreSimulator/Devices/xxxxxxx/data/Containers/Bundle/Application/xxxxxxxx/Project.app/Project
  Expected in: /Users/ning/Library/Developer/CoreSimulator/Devices/xx/data/Containers/Bundle/Application/xxx/Project.app/Frameworks/YBImageBrowser.framework/YBImageBrowser
 in /Users/ning/Library/Developer/CoreSimulator/Devices/cccc/data/Containers/Bundle/Application/ccc/Project.app/Project

**Comment by indulgeIn** [comment]
找不到 YBIBImageData 的符号，这种问题应该在工程里面很好排查吧，再对比一下demo？

**Comment by cheng77** [comment]
谢谢哈 ，我再排查下看看！


------------------ 原始邮件 ------------------
发件人: "波儿菜"<notifications@github.com>;
发送时间: 2019年8月3日(星期六) 中午11:02
收件人: "indulgeIn/YBImageBrowser"<YBImageBrowser@noreply.github.com>;
抄送: "宁"<804774355@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [indulgeIn/YBImageBrowser] 模拟器直接崩溃到该位置，请看下是什么问题？ (#182)




找不到 YBIBImageData 的符号，这种问题应该在工程里面很好排查吧，再对比一下demo？

**Comment by cheng77** [comment]
应该是cocoapod缓存问题，我这边再次把文件删除 重新pod，问题解决了！
