### ISSUE TITLE
你好，pod 安装后引入#import "YBImageBrowser.h" 使用时出现如下错误

### ISSUE THREAD

**Issue by lifewahaha** [indulgeIn/YBImageBrowser#183]
![image](https://user-images.githubusercontent.com/12185620/62480192-c4df3d80-b7e1-11e9-8b70-5cc0c8a306bf.png)

**Comment by lifewahaha** [comment]
没有这个YBIBImageData类呀，搜了pod的项目也没结果

**Comment by indulgeIn** [comment]
这是旧版的更新本地repo
