### ISSUE TITLE
SDWebImage 5.1.0 出来了

### ISSUE THREAD

**Issue by CoderSimonWong** [indulgeIn/YBImageBrowser#184]
还没有兼容 SDWebImage 5.1.0

**Comment by indulgeIn** [comment]
咋了，SDWebImage 又没有做好向下兼容？

**Comment by CoderSimonWong** [comment]
[!] CocoaPods could not find compatible versions for pod "SDWebImage":
  In Podfile:
    SDWebImage (~> 5.1.0)

    YBImageBrowser (~> 3.0.3) was resolved to 3.0.3, which depends on
      YBImageBrowser/Core (= 3.0.3) was resolved to 3.0.3, which depends on
        SDWebImage (~> 5.0.0)

pod YBImageBrowser 3.0.3  SDWebImage 自动 pod 为 5.0.6
强制 pod SDWebImage 5.1.0    YBImageBrowser 就是 2.1.5 版本了

**Comment by hms040717007** [comment]
问题同上,兼容sd有问题

**Comment by indulgeIn** [comment]
最新版已经对 SDWebImage 向上模糊依赖，并能支持不依赖 SDWebImage，详情见 README 相关描述。
