### ISSUE TITLE
框架没法设置状态栏是白色

### ISSUE THREAD

**Issue by gaohengwei** [indulgeIn/YBImageBrowser#186]
作者你好,我使用该框架没法设置状态栏.我们的需求状态栏是白色的.请问该怎么处理啊,

**Comment by indulgeIn** [comment]
设置 shouldHideStatusBar 为 NO 可不隐藏状态栏，至于颜色不是框架控制的。

**Comment by SailorGa** [comment]
可以抛出个结束预览的事件
