### ISSUE TITLE
最新版本3.0.2 ，最新修改的代码没有拉下来

### ISSUE THREAD

**Issue by leisong1125** [indulgeIn/YBImageBrowser#187]
pod 更新本地仓库后，更新版本到最新，代码没有拉下来
<img width="562" alt="屏幕快照 2019-08-06 18 53 22" src="https://user-images.githubusercontent.com/14797836/62534363-8eee9780-b87b-11e9-9941-d1512ade5b1f.png">
<img width="450" alt="屏幕快照 2019-08-06 18 53 10" src="https://user-images.githubusercontent.com/14797836/62534376-9615a580-b87b-11e9-91d5-534515bfbc82.png">
<img width="564" alt="屏幕快照 2019-08-06 18 53 47" src="https://user-images.githubusercontent.com/14797836/62534395-9dd54a00-b87b-11e9-8a78-9ff0d4f015fb.png">
<img width="953" alt="屏幕快照 2019-08-06 18 52 58" src="https://user-images.githubusercontent.com/14797836/62534419-b34a7400-b87b-11e9-8db9-340ccededb76.png">

**Comment by indulgeIn** [comment]
更新了 3.0.3，抱歉之前版本指针搞错了
