### ISSUE TITLE
浏览图片的时候，能不能在未加载完成的时候不显示黑屏啊

### ISSUE THREAD

**Issue by kenanwangyi** [indulgeIn/YBImageBrowser#19]
打开的时候，首先展示的是略缩图，然后出现加载的转圈框，加载的时候是黑屏，能不能这时候先显示略缩图，加载完成的时候在移除？

**Comment by indulgeIn** [comment]
目前加载框不会遮盖缩略图，请检查是否是最新代码，或者检查是否设置成功了缩略图（ YBImageBrowserModel 的 previewModel 属性）。

**Comment by kenanwangyi** [comment]
看到了看到了，谢谢大神

**Comment by liuxz656** [comment]
加载GIF的时候 还是会出现黑屏

**Comment by indulgeIn** [comment]
2.0 重做版本已更新  只要设置了sourceobject就不用设置缩略图了
