### ISSUE TITLE
可不可以放开SDWebImage版本控制

### ISSUE THREAD

**Issue by FantasticSkyBaby** [indulgeIn/YBImageBrowser#193]
如题，SD升级大版本后应该没这么快有大改动，所以建议放开依赖版本限制

**Comment by FantasticSkyBaby** [comment]
项目中其他库升级SD后，YB只能匹配2.1.5，目前只能手动修改本地repo
1、cd ~/.cocoapods/repos
2、search 并 cd  YBImageBrowser 找到3.x.x 目录下YBImageBrowser.podspec.json
3、修改SD版本限制

**Comment by indulgeIn** [comment]
最新版已经对 SDWebImage 向上模糊依赖，并能支持不依赖 SDWebImage，详情见 README 相关描述。
