### ISSUE TITLE
不知道是横屏兼容有问题，还是 iPad 兼容有问题

### ISSUE THREAD

**Issue by CoderSimonWong** [indulgeIn/YBImageBrowser#194]
点击图片的时候，应该显示 图片3 的情况，然而现在显示的是 图片2 的情况。

<img width="1085" alt="1" src="https://user-images.githubusercontent.com/13744200/63143280-14164100-c020-11e9-8c2c-f3cf9ac96efe.png">
<img width="1085" alt="2" src="https://user-images.githubusercontent.com/13744200/63143282-15476e00-c020-11e9-9cdb-9aa02f46d8bf.png">
<img width="1063" alt="3" src="https://user-images.githubusercontent.com/13744200/63143283-15476e00-c020-11e9-869f-b2ed1447dace.png">

**Comment by indulgeIn** [comment]
YBIBImageData 的 defaultLayout 里面有属性可以设置横屏/竖屏的填充方式

**Comment by CoderSimonWong** [comment]
好的，谢谢
