### ISSUE TITLE
第一张图片双击放大之后,向左滑动滑到图片尽头的时候回出现回弹

### ISSUE THREAD

**Issue by gaohengwei** [indulgeIn/YBImageBrowser#196]
第一张图片双击放大之后,向左滑动滑到图片尽头的时候回出现回弹,该如何解决?
![WeChat295270feb7d85cb317cfd28f99eb4577-min](https://user-images.githubusercontent.com/16328779/63327817-84df9500-c361-11e9-8a86-669ba8ab3210.png)

**Comment by indulgeIn** [comment]
这是正常的交互效果吧，如果关闭回弹有些效果将做不了

**Comment by gaohengwei** [comment]
现在是只有第一张图片有这个回弹效果，再往后滑动，其他的图片都没有这个效果，

**Comment by indulgeIn** [comment]
修复了问题，未更新pods版本
