### ISSUE TITLE
预览图自定义问题

### ISSUE THREAD

**Issue by zhangwenhaha** [indulgeIn/YBImageBrowser#198]

**Comment by indulgeIn** [comment]
YBIBImageData 的以下两个属性就是设置缩约图的，它们优先级都高于直接获取映射视图的图片。

/// 预览图/缩约图，注意这个图片不能过大（若 projectiveView 存在且是 UIImageView 类型将会自动获取缩约图）
@property (nonatomic, strong, nullable) UIImage *thumbImage;
/// 预览图/缩约图 URL，缓存中未找到则忽略（若 projectiveView 存在且是 UIImageView 类型将会自动获取缩约图）
@property (nonatomic, copy, nullable) NSURL *thumbURL;
