### ISSUE TITLE
浏览大图bug

### ISSUE THREAD

**Issue by xiaohuapunk** [indulgeIn/YBImageBrowser#201]
浏览高清大图存在bug，双指放大后总是会偏移到左上角固定的位置，可以用我上次的图片测试一下
[15M.zip](https://github.com/indulgeIn/YBImageBrowser/files/3545205/15M.zip)

**Comment by indulgeIn** [comment]
库版本多少呢

**Comment by xiaohuapunk** [comment]
> 库版本多少呢

 你好，直接 clone 的 master 分支，把图片放到系统相册中，两个浏览相册的示例都可以复现此问题
