### ISSUE TITLE
【需求】支持循环浏览

### ISSUE THREAD

**Issue by xiaohuapunk** [indulgeIn/YBImageBrowser#202]
代码写的非常棒，请问近期有计划支持循环浏览吗？

**Comment by indulgeIn** [comment]
不会做，循环浏览和现在的代码设计有冲突，并且感觉浏览图片不适合做成循环。。

**Comment by xiaohuapunk** [comment]
> 不会做，循环浏览和现在的代码设计有冲突，并且感觉浏览图片不适合做成循环。。

感谢回复，我自己处理一下
