### ISSUE TITLE
设置 thumbURL 界面过渡不平滑

### ISSUE THREAD

**Issue by cabbageTingZhang** [indulgeIn/YBImageBrowser#204]
### Description

如标题

### Environment

* YBImageBrowser version:master 分支最新代码
* iOS version:12.3 iPhone 6

**Comment by cabbageTingZhang** [comment]
[问题视频](http://www.iqiyi.com/w_19s9xaucvt.htmll), 希望作者给予答复

**Comment by indulgeIn** [comment]
你的映射视图是UIImageView么

**Comment by cabbageTingZhang** [comment]
是的, 设置映射识图的代码为:
XPMessageImageTableViewCell *cell = (XPMessageImageTableViewCell *)[self cellForRowAtIndexPath:[NSIndexPath indexPathForRow:[imageIndexKey integerValue]  inSection:0]];
pictureModel.projectiveView = cell ? cell.thumbImageView : nil;
就算不设置映射图, 界面还是不会很流畅, 但是要比设置映射识图的要好点, 我再录制一个[不设置映射识图的视频](http://www.iqiyi.com/w_19s9xdgjlx.html)

**Comment by indulgeIn** [comment]
很奇怪 没出现过这种问题 贴一下配置代码呢

**Comment by cabbageTingZhang** [comment]
找到原因了,我设置了data.thumbURL = [NSURL URLWithString:thumbImageUrlStr];
如果去掉thumbURL, 就变得很流畅了

**Comment by cabbageTingZhang** [comment]
我也是很郁闷, 我就设置了thumbURL而已,
YBIBImageData *data = [YBIBImageData new];
data.thumbURL = [NSURL URLWithString:thumbImageUrlStr];
 然后就变成这样了, 估计thumbURL的逻辑有点问题, 我一会儿再补充一个去掉thumbURL后的视频

**Comment by indulgeIn** [comment]
嗯应该代码有问题，空了我去看看
