### ISSUE TITLE
YBImageBrowser展示视频调用hide后，再展示视频底部背景变成透明的了

### ISSUE THREAD

**Issue by jiaoshier** [indulgeIn/YBImageBrowser#211]
### Description

YBImageBrowser初始为属性后，进行展示视频后，调用hide方法后，再次点击视频进行展示后，底部背景会变成透明的，拖动后背景再次变黑。

### Environment

* YBImageBrowser version:3.0.4
* iOS version: iPhone xs 12.4

**Comment by indulgeIn** [comment]
目前来说建议不复用 YBImageBrowser，状态复位上还存在一些问题。

**Comment by jiaoshier** [comment]
嗯 后面我看看有没有别的办法处理这个问题，自己修改一下代码。
