### ISSUE TITLE
图片点击退出的时候崩溃了

### ISSUE THREAD

**Issue by jiaoshier** [indulgeIn/YBImageBrowser#213]
### Description
控制台输入为
Cannot form weak reference to instance (0x106b1cd10) of class YBImageBrowser. It is possible that this object was over-released, or is in the process of deallocation.

browser作为了控制器的属性使用了，引用需要对图片浏览进行刷新

删除数据后调用 browser reloadData方法，在页面VC执行dealloc后，崩溃在
```objc
- (instancetype)initWithBrowser:(YBImageBrowser *)browser {
    if (self = [super init]) {
        _browser = browser;
        _rotating = NO;
        _supportedOrientations = UIInterfaceOrientationMaskAllButUpsideDown;
        _rotationDuration = 0.25;
    }
    return self;
}

```

_browser 查看为nil， 打印台内容为 Cannot form weak reference to instance (0x106b1cd10) of class YBImageBrowser. It is possible that this object was over-released, or is in the process of deallocation.

还有 YBImageBrowser 的 dealloc调用了rebuild是为什么，但是注释  YBImageBrowser 的 dealloc方法后，再次删除后刷新按钮未见崩溃

### Environment

* YBImageBrowser version:3.0.4
* iOS version:iPhone XR 12.4

**Comment by indulgeIn** [comment]
看起来逻辑是有问题的，dealloc 实际上不需要调用 rebuild，只需要复位对外部业务的修改，主要是在非触发出场效果的释放情况下有用。

**Comment by jiaoshier** [comment]
暂时没有问题，后续有时间我再看看需要怎么处理好点。
