### ISSUE TITLE
返回到占位图前，可以添加一个判断，，如果动画的视图对应的占位图不在屏幕内，可以做一个淡出动画,之前说已经添加了这个功能，但是新版本好像又移除了

### ISSUE THREAD

**Issue by NSObject-RC** [indulgeIn/YBImageBrowser#214]
例如：banner轮播图中，点击查看图片，滑动到第二张第三张，，返回的时候应该做个淡入的动画体验好点

* YBImageBrowser version:
* iOS version:

**Comment by indulgeIn** [comment]
新版本没有移除呢，可以通过 YBImageBrowser 的 defaultAnimatedTransition 属性调整动画时间。
