### ISSUE TITLE
最新版本，点击第一张浏览，滑动到第三张。点击消失到时候，消失到位置还是在第一张。发现无论起点从第几张开始，消失的cell都是第一个

### ISSUE THREAD

**Issue by 18094156787** [indulgeIn/YBImageBrowser#217]
最新版本，点击第一张浏览，滑动到第三张。点击消失到时候，消失到位置还是在第一张。发现无论起点从第几张开始，消失的cell都是第一个
- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath {
    JNImgCollectionViewCell *cell = (JNImgCollectionViewCell *)[collectionView cellForItemAtIndexPath:indexPath];
    // 图片预览
    NSMutableArray *datas = [NSMutableArray array];
    [self.model.image enumerateObjectsUsingBlock:^(NSString *_Nonnull urlStr, NSUInteger idx, BOOL * _Nonnull stop) {
        
        // 网络图片
        YBIBImageData *data = [YBIBImageData new];
        data.imageURL = [NSURL URLWithString:urlStr];
        data.projectiveView = cell.imgView;
        [datas addObject:data];
    }];
    
    YBImageBrowser *browser = [YBImageBrowser new];
    browser.dataSourceArray = datas;
    browser.currentPage = indexPath.row;
    [browser show];
}

**Comment by indulgeIn** [comment]
每一个 data 对应一个 projectiveView 做出入场动效，你这里都设为了点击的那个。

**Comment by 18094156787** [comment]
我看demo也是这么写的，请问要修改哪里呢

**Comment by 18094156787** [comment]
> 每一个 data 对应一个 projectiveView 做出入场动效，你这里都设为了点击的那个。

我看demo也是这么写的，请问要修改哪里呢

**Comment by indulgeIn** [comment]
demo 里面是拿到了每一个可见的 indexPath 的 cell 的 imageView，赋值给对应的 data。

**Comment by 18094156787** [comment]
> demo 里面是拿到了每一个可见的 indexPath 的 cell 的 imageView，赋值给对应的 data。

好的，我明白了哈，谢谢。
