### ISSUE TITLE
闪一下

### ISSUE THREAD

**Issue by CoderSimonWong** [indulgeIn/YBImageBrowser#22]
在加载图片的时候出现 HUD，可是HUD结束的那一瞬间会闪一下才出现原图，能不能做到像微信一样，不会闪那一下。这个是我们公司后端提出的问题😂

**Comment by ChandHsu** [comment]
是的,闪一下看着很不舒服

**Comment by indulgeIn** [comment]
@CoderSimonWong @ChandHsu 在转场进入图片浏览器时，若传递了点击对应的imageview会有一个转场动效，但是转场结束过后，由于没有缩约图屏幕会变黑，加载过快导致会有闪一下的视觉效果。

所以解决方案之一就是为点击入场的那个 YBImageBrowserModel 设置缩约图（当然给所有都设置缩略图会避免出现加载图片时背景变黑只有一个加载指示器的情况）。

解决方案之二是要改组件代码了，因为若传递了点击对应的imageview实际上已经可以拿到入场的这个缩略图了。不过作者最近比较忙，后续会做重构和迭代，所以用第一种方案解决吧。

**Comment by indulgeIn** [comment]
2.0 重做版本已更新  新版本设置了sourceobject不需设置缩略图

**Comment by 1xiaocainiao** [comment]
> 2.0 重做版本已更新 新版本设置了sourceobject不需设置缩略图

第一张图依然会闪烁一下，其他的就不会了
