### ISSUE TITLE
我这种链接会崩溃

### ISSUE THREAD

**Issue by linger997** [indulgeIn/YBImageBrowser#221]
http://cdn.gxhuihuang.cn/eagle/2839/house/2019/05/25/17/21b1bf0bf2ad6210647b8f7c60ba60002a1de754245.jpg?x-oss-process=image/resize,m_fixed,w_300

**Comment by indulgeIn** [comment]
并没有崩溃呀，查一下崩溃日志可能不是这个库导致的。

**Comment by linger997** [comment]
已经找到了谢谢
