### ISSUE TITLE
projectView 转场动画往回缩的时候，位置不对应

### ISSUE THREAD

**Issue by zhangwenhaha** [indulgeIn/YBImageBrowser#227]
### Description
就是我present一个控制器之后不做任何操作，然后dismiss这个控制器，在点击图片hide，会发现图片缩回去的位置并不是原始位置，projecview的地址在present控制器前后以及hide图片浏览器整个过程都是没有变的

### Environment

* YBImageBrowser version:3.0.4
* iOS version:所有版本都会出现

**Comment by indulgeIn** [comment]
不是非常明白这个场景，有更多描述么

**Comment by zhangwenhaha** [comment]
链接: https://pan.baidu.com/s/1Mw5bdzLQnaJOtHHAKJxZ9Q 提取码: xx56 
我录制一段视频可以看一下，就是图片在hide的时候，如果没有进行present操作是正常的，但是如果进行了present操作，在返回就会有问题

**Comment by zhangwenhaha** [comment]
还有一个问题就是ios13.1 状态栏不能隐藏了

**Comment by indulgeIn** [comment]
前面个问题可能是你操作过后调用了 reloadData 让 Cell 内存块位置变了

**Comment by zhangwenhaha** [comment]
reloadData我这边确实有，但是我注释了那部分问题依然存在，我打印cell对应的projectView内存地址在present之前以及hidden时并没有发生变化，只不过对应的image发生了变化这就很奇怪了
present前：
<UIImageView: 0x10fb1e9e0; frame = (0 0; 98 98); clipsToBounds = YES; opaque = NO; autoresize = RM+BM; userInteractionEnabled = NO; layer = <CALayer: 0x28186b840>>  <UIImage: 0x28337e4c0> size {720, 1280} orientation 0 scale 1.000000

hidden时：
<UIImageView: 0x10fb1e9e0; frame = (0 0; 98 98); clipsToBounds = YES; alpha = 0; opaque = NO; autoresize = RM+BM; userInteractionEnabled = NO; layer = <CALayer: 0x28186b840>>  <UIImage: 0x2833632c0> size {1440, 2560} orientation 0 scale 1.000000

然后发现iOS13.1 present方式不是全覆盖的那种，这个问题就没有出现

**Comment by zhangwenhaha** [comment]
我好像明白你意思了。。reloadData操作不是指的图片浏览器而是本身那个展示的九宫格发生了reloaddata操作才会导致有这个问题出现

**Comment by kule123** [comment]
我也出现这个问题 视图没变但是动画位置变了样 怎么解决的
