### ISSUE TITLE
如何动态更改frame 呢？

### ISSUE THREAD

**Issue by wofl521WLF** [indulgeIn/YBImageBrowser#230]
如何动态更改frame 呢？，比如我小图模式下浏览，双击后，变为全屏，类似系统相册那样

**Comment by indulgeIn** [comment]
这个只能单张浏览，不包含外部业务。

**Comment by wofl521WLF** [comment]
> 这个只能单张浏览，不包含外部业务。
我觉得这个不是外部业务啊，这个在最初的时候，showinView 给予 contentSize 过后，后期，后面应该可以动态更改啊

**Comment by wofl521WLF** [comment]
嗯嗯，建议，后期可以加上这个，😄
