### ISSUE TITLE
视频播放封面图片比较大的情况下，视频播放时封面图片还能看见

### ISSUE THREAD

**Issue by LIULIUQIAN** [indulgeIn/YBImageBrowser#232]

**Comment by LIULIUQIAN** [comment]
<img width="374" alt="WeChat0924aa785a622cb87b93769b2013a61a" src="https://user-images.githubusercontent.com/4877489/66635237-52effe00-ec41-11e9-8b36-46a921a6aeb1.png">

**Comment by coooliang** [comment]
我也是这样，请问怎么解决呢？！~
