### ISSUE TITLE
转场endTransitioningWithIsShow的代理方法isShow貌似不准确

### ISSUE THREAD

**Issue by zhangwenhaha** [indulgeIn/YBImageBrowser#235]
### Description
isShow 从图片浏览器show到hide一直都是1
![image](https://user-images.githubusercontent.com/16064900/66697877-10dfbe80-ed0c-11e9-8889-91d7c1f826d4.png)

### Environment

* YBImageBrowser version:
* iOS version:

**Comment by li-qingnan** [comment]
遇见相同问题，结束转场的代理方法，isShow一直都是YES，希望作者及时修复。
