### ISSUE TITLE
iOS13 系统，非异形屏手机，视频播放上方操作按钮都快贴到状态栏啦

### ISSUE THREAD

**Issue by zhangwenhaha** [indulgeIn/YBImageBrowser#236]
### Description
![image](https://user-images.githubusercontent.com/16064900/67075226-59402600-f1bd-11e9-840a-1e9fdfcca43a.png)

### Environment

* YBImageBrowser version:3.0.6
* iOS version:iOS13

**Comment by indulgeIn** [comment]
#231
