### ISSUE TITLE
YBImageBrowser能不能基于UIViewController

### ISSUE THREAD

**Issue by kingstarwmx** [indulgeIn/YBImageBrowser#238]
YBImageBrowser现在的做法，show的时候是加在了keywindow上,在后序自定义toolBar的时候如果需要再push到其他页面的时候(参考微信)不太方便,希望改进

**Comment by indulgeIn** [comment]
看 DEMO 有案例

**Comment by kingstarwmx** [comment]
我看了demo好像没我说的这种情况呀，我看了添加到控制器使用（以相册为例)那个，动画效果就没了，我现在的需求就是类似微信一样，点击聊天页面某一张图片，然后动画的方式展示出来，再点击右上角的一个图标可以查看当前聊天的所有图片，这个时候应该是push到另一个vc的

**Comment by kingstarwmx** [comment]
要想有动画必须放show的方法，viewWillAppear里面才行，但是效果有缺陷

**Comment by kingstarwmx** [comment]
一旦加在keywindow上，想要再页面间跳转就很蛋疼了，想push到另一个vc，不知道怎么能实现

**Comment by indulgeIn** [comment]
可以添加到指定view
