### ISSUE TITLE
如何实现预览的时候删除某一张图片刷新界面

### ISSUE THREAD

**Issue by ZhangXiao233** [indulgeIn/YBImageBrowser#24]
需求是预览时右上角删除, 删除后刷新数据源

虽然备注写了不要尝试刷新数据源 但还是想尝试

- (void)setDataArray:(NSArray<YBImageBrowserModel *> *)dataArray {
    if (!dataArray || !dataArray.count) {
        YBLOG_ERROR(@"dataArray is invalid");
        return;
    }
    _dataArray = dataArray;
    [self numberInYBImageBrowserView:_browserView];
    [_browserView reloadData];
}

我在这个方法中尝试reload列表. 还有什么思路吗  还是根本不支持这种删除操作

**Comment by indulgeIn** [comment]
2.0 重做版本已更新 支持重载数据
