### ISSUE TITLE
加载网络图片的时候，设置本地的默认图，转场的时候会闪一下

### ISSUE THREAD

**Issue by iamlay** [indulgeIn/YBImageBrowser#240]
### Environment

* YBImageBrowser version:
* iOS

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by indulgeIn** [comment]
做移动平滑动效时，会使用`projectiveView`来做。而你如果设置了一张和`projectiveView`不一致的图片，切换时就会出现不平滑的效果。

理论上只要设置`projectiveView`了就不需要再去设置占位图了；否则你可以将入场动画改为其它的，比如渐隐。
