### ISSUE TITLE
iOS 13状态栏都无法隐藏

### ISSUE THREAD

**Issue by wangliujiayou** [indulgeIn/YBImageBrowser#241]
![50A910BD48F052707351A428CEF55B9C](https://user-images.githubusercontent.com/18564430/67614001-886f1c80-f7e7-11e9-8701-bad02b85c037.JPG)
![24B948B7CD2CA4DE4381E21A846AB9A9](https://user-images.githubusercontent.com/18564430/67614002-8907b300-f7e7-11e9-8c10-6b364e351104.JPG)

**Comment by indulgeIn** [comment]
#231
