### ISSUE TITLE
YBIBImageData

### ISSUE THREAD

**Issue by carry1024** [indulgeIn/YBImageBrowser#249]
YBIBImageData 这个模型里面可不可以支持一下UIImage的实例，我的浏览列表是一个UIImage的数组，但是我没法加入到YBIBImageData当中。

**Comment by indulgeIn** [comment]
有一个闭包属性呀 找找

**Comment by carry1024** [comment]
太感谢了。我以为这个属性是用来返回你之前加入的。

**Comment by indulgeIn** [comment]
解决了就好
