### ISSUE TITLE
视屏播放部分机器没有声音

### ISSUE THREAD

**Issue by 627969687** [indulgeIn/YBImageBrowser#250]
### Description
部分系统播放视屏只有画面没有声音
>>>添加如下代码可修复
![image](https://user-images.githubusercontent.com/20868764/68266438-1968b200-008a-11ea-9955-e7ed52f1fe6b.png)

### Environment

* YBImageBrowser version:  3.x 
* iOS version: 13.1.3、11.3.1

**Comment by indulgeIn** [comment]
这种代码外部设置就好，这个repo简单的播放器还是跟随系统较好

**Comment by guigenyi** [comment]
多谢，我也遇到了同样的问题
