### ISSUE TITLE
关于在YBIBImageCell上的定制化

### ISSUE THREAD

**Issue by devcxm** [indulgeIn/YBImageBrowser#254]
首先很感谢作者开源这么好的库，能够很方便的集成到项目中，且可高度定制化。现将项目使用中遇到的一些定制问题提两个建议，作者考虑可否修改一下。
1、将YBIBImageCell的`YBIBImageScrollView *imageScrollView`属性公开放到头文件，因为我在定制cell继承YBIBImageCell，需要改`YYAnimatedImageView *imageView`的背景颜色（PS：透明图，黑色文字在黑色背景看不到。重新实现YBIBImageCell太复杂没必要，目前通过遍历contentView子视图获取）；
2、图片放大时是否能够通知YBIBToolViewHandler当前cell的zoomScale，比如在图片放大时需要隐藏某个工具栏。

**Comment by indulgeIn** [comment]
第一个问题建立了 Cell 的 YBIBImageCell+Internal 文件，继承类导入就行 。
第二个问题，由于工具栏和具体的 Cell 最好不数据流动耦合，所以可以这么做：YBIBImageData -> imageDidZoomBlock 回调中取调用 YBImageBrowser -> toolViewHandlers
