### ISSUE TITLE
只传入一个视频，点击不能播放

### ISSUE THREAD

**Issue by YY873267521** [indulgeIn/YBImageBrowser#255]
### Environment

* YBImageBrowser version:
* iOS version:

**Comment by indulgeIn** [comment]
已修复，暂未打 release 包

**Comment by YY873267521** [comment]
刚测试，已经解决单个视频无法播放问题。 谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"波儿菜"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月23日(星期一) 中午11:27
收件人:&nbsp;"indulgeIn/YBImageBrowser"<YBImageBrowser@noreply.github.com&gt;;
抄送:&nbsp;"ゝ      Miss  Q ゜"<873267521@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [indulgeIn/YBImageBrowser] 只传入一个视频，点击不能播放 (#255)



已修复，暂未打 release 包

**Comment by indulgeIn** [comment]
pods 3.0.8 版本更新   这确实是个严重的 bug
