### ISSUE TITLE
无法用YYWebImage替换SD

### ISSUE THREAD

**Issue by sandychales** [indulgeIn/YBImageBrowser#26]
![1536133585831](https://user-images.githubusercontent.com/13314828/45078570-f7407080-b122-11e8-8dc4-2ae3c8348b7e.jpg)

发现无法方便的用YY替换SD，因为YY的completion返回值中，没有NSData，导致外面无法根据NSData获取到图片类型，如gif类型

**Comment by NSObject-RC** [comment]
我项目有YYWeb，也有SDWeb，动画和缓存方面感觉YY比SD好点，还有YYKit这个是真心好用，，但是很蛋疼的是作者不更新了，已经两年了，😔

**Comment by indulgeIn** [comment]
确实无法替换了，组件API用法过深。
