### ISSUE TITLE
结束转场的代理方法 endTransitioningWithIsShow，isShow一直是YES

### ISSUE THREAD

**Issue by li-qingnan** [indulgeIn/YBImageBrowser#269]
### Description

结束转场的代理方法 endTransitioningWithIsShow，isShow不管是入场还是出场，一直是YES。
我看提交记录上 10月26日，git id:838f05c, 标记已经fixed[#235](https://github.com/indulgeIn/YBImageBrowser/issues/235)，但是目前的版本还是有这个问题。
请作者看一下，希望尽快更新，谢谢。

### Environment

* YBImageBrowser version: 我使用的pod方式的 YBImageBrowser/Video，3.0.6版本
* iOS version: 12.4.1

**Comment by indulgeIn** [comment]
才更新，之前改了没传pods

**Comment by li-qingnan** [comment]
pod没有搜索到啊，现在最新的还是3.0.6

**Comment by indulgeIn** [comment]
需要更新一下本地索引

**Comment by li-qingnan** [comment]
更新3.0.7版本，造成视频播放不了了
