### ISSUE TITLE
在发布新的release版本的时候不要删除以前的版本呀

### ISSUE THREAD

**Issue by MrZhou1990** [indulgeIn/YBImageBrowser#27]

**Comment by indulgeIn** [comment]
不好意思，之前的release版本bug比较多，只保留了 1.1.2 版本。
我目前在重做这个库，大改架构，优化性能和代码，还有几天就可以出来了，所以删除了之前的版本，到时候希望大家尽量替换成最新的，目前版本的代码我不再维护了。
见谅。。

**Comment by MrZhou1990** [comment]
作者你好，你写的这个库非常的棒，给你一个大大赞👍
加油！




在2018年09月12日 16:49，杨波<notifications@github.com> 写道：

不好意思，之前的release版本bug比较多，只保留了 1.1.2 版本。
我目前在重做这个库，大改架构，优化性能和代码，还有几天就可以出来了，所以删除了之前的版本，到时候希望大家尽量替换成最新的，目前版本的代码我不再维护了。
见谅。。

**Comment by indulgeIn** [comment]
2.0 重做版本已更新
