### ISSUE TITLE
加载URL形式的视频，播放不了显示黑屏

### ISSUE THREAD

**Issue by li-qingnan** [indulgeIn/YBImageBrowser#271]
加载URL形式的视频，播放不了显示黑屏。
同样的url地址放在demo里是可以播放的，但是通过pod集成到项目里，就不能播放了。
请问作者，如何排查和解决。

### Environment

* YBImageBrowser version: pod版本，3.0.7
* iOS version: 12.4.1

**Comment by li-qingnan** [comment]
昨天由于更新本地索引，把其他的pod库也更新了，现在全都回退了，视频可以播放了，
未知是哪个类库对 YBImageBrowser 有影响导致视频播放不了。

**Comment by li-qingnan** [comment]
我回退后又更新了一下 YBImageBrowser 到3.0.7，视频又播放不了了，黑屏，好崩溃。

**Comment by li-qingnan** [comment]
一头雾水，不知道什么原因造成的。

**Comment by ElfSundae** [comment]
我也是.. 前两天提交审核时 pod update 了以下.. 刚才发现视频黑屏

**Comment by ElfSundae** [comment]
`pod 'YBImageBrowser', '3.0.6'` 指定版本就解决了，前两天发布的 3.0.7 有问题。

**Comment by indulgeIn** [comment]
方便扔个视频地址么，我这里3.0.7能播放呀

**Comment by ElfSundae** [comment]
不是视频地址的问题，我这边是黑屏不能播放，没播放按钮，但是可以保存，下载然后保存。
```objc
YBIBVideoData *videoData = [YBIBVideoData new];
videoData.videoURL = (messageObject.url
                     ? [NSURL URLWithString:messageObject.url]
                     : [NSURL fileURLWithPath:messageObject.path]);
videoData.thumbImage = [UIImage imageWithContentsOfFile:messageObject.thumbPath];

YBImageBrowser *browser = [YBImageBrowser new];
browser.dataSourceArray = @[ videoData ];
[browser show];
```

**Comment by ElfSundae** [comment]
我也是刚用这个库，没调试内部实现。明天抽空看看是啥原因

**Comment by ElfSundae** [comment]
@indulgeIn 问题应该在这：https://github.com/indulgeIn/YBImageBrowser/commit/838f05ccbc4ebe798ff93e0bd7425661cbe3d4db#diff-ce69b3897834c96d30fa65d308bb2fcaR191-L195
```objc
[self setTransitioning:YES isShow:YES];
[self.animatedTransition yb_showTransitioningWithContainer:self startView:startView startImage:startImage endFrame:endFrame orientation:self.rotationHandler.currentOrientation completion:^{
    [self setTransitioning:NO isShow:YES];
    [self build];
}];
```

```objc
- (id<YBIBVideoDataDelegate>)delegate {
    // Stop sending data to the '_delegate' if it is transiting.
    return self.yb_isTransitioning() ? nil : _delegate;
}
```

`build` 方法里获取 delegate 时为 nil ，delegate 的方法都没有被调用。

![image](https://user-images.githubusercontent.com/526008/71306525-56abb800-241c-11ea-9fdd-41cfdd6e4a11.png)

**Comment by indulgeIn** [comment]
已修复问题，pods 3.0.8 版本更新
