### ISSUE TITLE
一点点优化建议

### ISSUE THREAD

**Issue by newdolphintime** [indulgeIn/YBImageBrowser#29]
您好,是否可以考虑实现一下在照片浏览器弹出的过程中将对应collectionview对应位置的imageview设置为空白,在下拉返回图片缩小到对应位置的时候再显示的功能,类似新版微博的效果

**Comment by newdolphintime** [comment]
或者说给一个动画执行完的回调方法也可以^_^

**Comment by indulgeIn** [comment]
2.0 重做版本已更新 支持这个功能

**Comment by indulgeIn** [comment]
2.0 重做版本已更新 支持这个功能
