### ISSUE TITLE
SDWebImage pods依赖版本冲突问题

### ISSUE THREAD

**Issue by maltsugar** [indulgeIn/YBImageBrowser#3]
冲突导致没办法安装，作者可不可以考虑，制作这个组件时不使用pod。建一个第三方库的目录，将SDWebImage和FLAnimatedImage，放进去。并都把类名都加一下自己的YB前缀。这样方便集成，不依赖其他pod版本，也方便使用这个库
```
[!] CocoaPods could not find compatible versions for pod "SDWebImage":
  In snapshot (Podfile.lock):
    SDWebImage (= 4.2.3, ~> 4.2.2)

  In Podfile:
    NIMKit/Full was resolved to 2.7.0, which depends on
      NIMKit/Core (= 2.7.0) was resolved to 2.7.0, which depends on
        SDWebImage (~> 4.2.2)

    YBImageBrowser was resolved to 1.0.7, which depends on
      SDWebImage (~> 4.3.3)

    ZLPhotoBrowser was resolved to 2.6.5, which depends on
      SDWebImage
```

**Comment by maltsugar** [comment]
嗯 这些是可以解决。但是需要花一点时间，我等空了再换你这个吧。主要是别人肯定没有作者熟悉组件，换肯定没有作者换快。需要一点成本

**Comment by xx-li** [comment]
@indulgeIn in有空了换一下吧。

**Comment by wjd759406594** [comment]
一样的  YBImageBrowser was resolved to 2.0.2, which depends on
      SDWebImage (~> 4.3.3)

**Comment by indulgeIn** [comment]
2.0.3 版本已经取消对三方库版本号的依赖。
由于 SD 3.x 之后版本没有做好向下兼容，所以用了老版本的 SD 而报错需自行替换方法；若 SD 目前的版本在将来无法向上兼容，我会更改库代码

**Comment by Mephsito23** [comment]
感觉很不错,但是我安装的最新版本2.0.8使用 pod 'YBImageBrowser' 导入时和 YYKit 框架有冲突,里面都有 YYImage文件,希望能解决下>_<

**Comment by indulgeIn** [comment]
方法一是把yykit拆开pod导入  方法二是手动导入该组件

**Comment by Coder-ZJ** [comment]
和SD冲突  安装完又卸了，建议作者去掉第三方依赖

**Comment by tzqiang** [comment]
自己的项目另外的一个库依赖是 4.2.3 ，demo 的 YBImageBrowser 现在依赖是 4.3.3 
自己的项目编译时 YBImageBrowser 报错
` [((SDWebImageDownloadToken *)token) cancel];  No visible @interface for 'SDWebImageDownloadToken' declares the selector 'cancel'`

**Comment by wanyijun** [comment]
SD要求是5.00的 之前有的库用的是4.3的 全报错了

**Comment by indulgeIn** [comment]
> SD要求是5.00的 之前有的库用的是4.3的 全报错了

使用 2.1.5 版本。

**Comment by ZengWeiJun** [comment]
同样问题，其实可以考虑将图片加载逻辑让用户自己实现，这样该组件就无需再依赖下载相关的第三方库

**Comment by ThisFriend** [comment]
> > SD要求是5.00的 之前有的库用的是4.3的 全报错了
> 
> 使用 2.1.5 版本。

不行呀，#import "YBIBWebImageManager.h" 文件中还是会与SDWebImage 4.2.3 冲突。

**Comment by indulgeIn** [comment]
@ThisFriend 这个库一开始依赖的 SD 4.4 ，2.1.7 之后依赖 SD 5.0，所以最好是升级 SD，或者改本库。

**Comment by ThisFriend** [comment]
> @ThisFriend 这个库一开始依赖的 SD 4.4 ，2.1.7 之后依赖 SD 5.0，所以最好是升级 SD，或者改本库。

OK，好的， 感谢。

**Comment by ThisFriend** [comment]
> 自己的项目另外的一个库依赖是 4.2.3 ，demo 的 YBImageBrowser 现在依赖是 4.3.3
> 自己的项目编译时 YBImageBrowser 报错
> ` [((SDWebImageDownloadToken *)token) cancel]; No visible @interface for 'SDWebImageDownloadToken' declares the selector 'cancel'`

老哥你这个问题这么解决的。

**Comment by ZengWeiJun** [comment]
不用cocoapods安装，直接下载下来该源码，手动拖拽到项目中
只需要改这个文件就行了：YBIBWebImageManager.m
| |
曾维俊
|
|
niuszeng@163.com
|
签名由网易邮箱大师定制


在2019年05月23日 10:13，ThisFriend<notifications@github.com> 写道：

自己的项目另外的一个库依赖是 4.2.3 ，demo 的 YBImageBrowser 现在依赖是 4.3.3
自己的项目编译时 YBImageBrowser 报错
[((SDWebImageDownloadToken *)token) cancel]; No visible @interface for 'SDWebImageDownloadToken' declares the selector 'cancel'

老哥你这个问题这么解决的。

**Comment by ThisFriend** [comment]
> 不用cocoapods安装，直接下载下来该源码，手动拖拽到项目中 只需要改这个文件就行了：YBIBWebImageManager.m | | 曾维俊 | | niuszeng@163.com | 签名由网易邮箱大师定制 在2019年05月23日 10:13，ThisFriend<notifications@github.com> 写道： 自己的项目另外的一个库依赖是 4.2.3 ，demo 的 YBImageBrowser 现在依赖是 4.3.3 自己的项目编译时 YBImageBrowser 报错 [((SDWebImageDownloadToken *)token) cancel]; No visible @interface for 'SDWebImageDownloadToken' declares the selector 'cancel' 老哥你这个问题这么解决的。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

感谢，虽然我自己已经改好了。
是把本项目2.1.5的YBIBWebImageManager里边的冲突代码改为了适配当前SDWebImage的

**Comment by jiutianhuanpei** [comment]
> > 不用cocoapods安装，直接下载下来该源码，手动拖拽到项目中 只需要改这个文件就行了：YBIBWebImageManager.m | | 曾维俊 | | [niuszeng@163.com](mailto:niuszeng@163.com) | 签名由网易邮箱大师定制 在2019年05月23日 10:13，ThisFriend[notifications@github.com](mailto:notifications@github.com) 写道： 自己的项目另外的一个库依赖是 4.2.3 ，demo 的 YBImageBrowser 现在依赖是 4.3.3 自己的项目编译时 YBImageBrowser 报错 [((SDWebImageDownloadToken *)token) cancel]; No visible @interface for 'SDWebImageDownloadToken' declares the selector 'cancel' 老哥你这个问题这么解决的。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 感谢，虽然我自己已经改好了。
> 是把本项目2.1.5的YBIBWebImageManager里边的冲突代码改为了适配当前SDWebImage的

你好，可以请教一下这个文件怎么改的吗

**Comment by ThisFriend** [comment]
> > > 不用cocoapods安装，直接下载下来该源码，手动拖拽到项目中 只需要改这个文件就行了：YBIBWebImageManager.m | | 曾维俊 | | [niuszeng@163.com](mailto:niuszeng@163.com) | 签名由网易邮箱大师定制 在2019年05月23日 10:13，ThisFriend[notifications@github.com](mailto:notifications@github.com) 写道： 自己的项目另外的一个库依赖是 4.2.3 ，demo 的 YBImageBrowser 现在依赖是 4.3.3 自己的项目编译时 YBImageBrowser 报错 [((SDWebImageDownloadToken *)token) cancel]; No visible @interface for 'SDWebImageDownloadToken' declares the selector 'cancel' 老哥你这个问题这么解决的。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
> > 
> > 
> > 感谢，虽然我自己已经改好了。
> > 是把本项目2.1.5的YBIBWebImageManager里边的冲突代码改为了适配当前SDWebImage的
> 
> 你好，可以请教一下这个文件怎么改的吗

应该是改成这个，很早的了。
   [[SDWebImageDownloader sharedDownloader] cancel:token];

**Comment by indulgeIn** [comment]
最新版已经支持选择是否依赖 SDWebImage 导入，详情见 README 相关描述。
