### ISSUE TITLE
defaultToolbar的保存按钮，保存失败

### ISSUE THREAD

**Issue by Fxxxxxx** [indulgeIn/YBImageBrowser#31]
图片是用url传递的，一直提示保存失败

**Comment by indulgeIn** [comment]
是偶发的么

**Comment by ZSMHup** [comment]
我这边也是，图片保存失败，视频可以保存

**Comment by Fxxxxxx** [comment]
> 是偶发的么

不是偶发，我集成之后，一直是保存失败的，图片用的url传递

**Comment by indulgeIn** [comment]
我这边无法重现，需要确认以下内容：
1、图片的格式
2、iOS系统版本号
3、是提示“保存失败”还是“无法保存”？
4、图片成功呈现在界面上了么？
5、或者自行排查一下，如下图：
![8b101827-e5fc-4b68-90f6-849af325c4db](https://user-images.githubusercontent.com/18362662/46124380-5c850e80-c256-11e8-96b8-5ae1f0117b06.jpeg)

**Comment by ZSMHup** [comment]
> 我这边无法重现，需要确认以下内容：
> 1、图片的格式
> 2、iOS系统版本号
> 3、是提示“保存失败”还是“无法保存”？
> 4、图片成功呈现在界面上了么？
> 5、或者自行排查一下，如下图：
> ![8b101827-e5fc-4b68-90f6-849af325c4db](https://user-images.githubusercontent.com/18362662/46124380-5c850e80-c256-11e8-96b8-5ae1f0117b06.jpeg)
1、我把图片链接放在你的demo里面是可以保存的，跟图片格式好像没什么关系
2、图片可以正常显示，保存提示“无法保存”
3、可以加下QQ吗？403549384

![1e755b8c0483cbfcadd9ba1c04741394](https://user-images.githubusercontent.com/20026815/46125017-bfc47000-c259-11e8-946f-bd2f34341d35.png)

**Comment by heyehao2008** [comment]
自己检查下工程里面的plist文件里面添加了保存图片到相册的key没有，保存图片也是需要添加key的。和申请相机访问类似

**Comment by ZSMHup** [comment]
> 自己检查下工程里面的plist文件里面添加了保存图片到相册的key没有，保存图片也是需要添加key的。和申请相机访问类似

都已添加和授权了

**Comment by indulgeIn** [comment]
@Fxxxxxx @ZSMHup 问题已解决，pods 2.0.2 版本已更新

**Comment by SHRemover** [comment]
单独使用 dataSource 代理数据源时，图片无法保存、视频可以保存。
而使用 dataSourceArray 数据源时就没有问题、
