### ISSUE TITLE
图片加载失败，不能返回

### ISSUE THREAD

**Issue by iwantFB** [indulgeIn/YBImageBrowser#34]
图片加载失败(未连接网络),遮罩导致不能返回

**Comment by iwantFB** [comment]
￼
![Uploading WechatIMG8.jpeg…]()

**Comment by iwantFB** [comment]
![wechatimg8](https://user-images.githubusercontent.com/27498843/46001378-b57d6700-c0dd-11e8-9438-25ee710c4ffe.jpeg)

**Comment by iwantFB** [comment]
可以在 ` - (void)showText:(NSString *)text click:(void(^)(void))click {} `
方法内加上
``
[UIView animateWithDuration:2.0 animations:^{
        self.alpha = 0;
    } completion:^(BOOL finished) {
        [self removeFromSuperview];
    }];
``

**Comment by indulgeIn** [comment]
问题已修复，pods 2.0.1 版本已更新，包含一些其它优化
