### ISSUE TITLE
图片下拉消失，能加个速度的判断吗？

### ISSUE THREAD

**Issue by donbe** [indulgeIn/YBImageBrowser#35]
在预览图片，下拉手势，现在好像是用距离判断的，能加一个速度判断，下拉比较快的时候，也让图片小时吗？

**Comment by PandexLee** [comment]
我实现了一下这个需求，可以让图片浏览器的体验会更好
在YBImageBrowserCell.m    line:446 增加实现一个代理方法可以实现这个需求

- (void)scrollViewWillEndDragging:(UIScrollView *)scrollView withVelocity:(CGPoint)velocity targetContentOffset:(inout CGPoint *)targetContentOffset{
    CGFloat duration = 200;    //velocity的单位是 point/ms ，预估动画时间为200ms
    totalOffsetYOfAnimateImageView -= velocity.y * duration;
    totalOffsetXOfAnimateImageView -= velocity.x * duration;
}

**Comment by PandexLee** [comment]
上面那个是我用的老版本的写法。。刚刚更新了新版2.0.x，新版的解决方案在这
@indulgeIn 希望可以新增这个feature

YBImageBrowseCell.m      line:234
        // END
        if (self->_isGestureInteraction) {
            CGPoint velocity = [pan velocityInView:self];
            CGFloat duration = 200;    //velocity的单位是 point/ms ，预估动画时间为200ms
            point.x -= velocity.y * duration;
            point.y -= velocity.x * duration;
            BOOL shouldDismiss = ABS(point.y - self->_gestureInteractionStartPoint.y) > self->_containerSize.height * self->_giProfile.dismissScale;
            if (shouldDismiss) {
                self.yb_browserDismissBlock();
            } else {
                [self restoreGestureInteractionWithDuration:self->_giProfile.restoreDuration];
            }
        }

**Comment by indulgeIn** [comment]
判断加了，中午才更新了 pods 版本，暂时不打版了。

**Comment by indulgeIn** [comment]
代码已优化，pods 2.0.5
