### ISSUE TITLE
图片太大总是加载失败！

### ISSUE THREAD

**Issue by zhifenx** [indulgeIn/YBImageBrowser#37]
你好，好像图片过大总是加载失败，图片大小有限制吗？在代码里没有看到相关设置。我只能限制上传的图片大小来解决这个问题吗？

**Comment by zhifenx** [comment]
我试着传入初始化YBImageBrowseCellData时传入YBImage，但是show的时候，图片会闪现，不是渐显的效果。

**Comment by indulgeIn** [comment]
下载图片没有限制是基于SDWebImage的；想要渐隐效果设置入场动效，因为默认是过渡的如果没传sourceObject就会失去过渡动效

**Comment by indulgeIn** [comment]
sourceObject传button.imageView吧。这个图片你试试其他地方能加载出来不？我这边不行

**Comment by zhifenx** [comment]
不好意思啊，我找到原因了，是我这边生成图片URL加时间戳时出现时偏差，导致URL与阿里云里的不一致，实在抱歉，非常感谢你的耐心解答。框架很棒！👍
