### ISSUE TITLE
有一个很奇葩的需求

### ISSUE THREAD

**Issue by ChandHsu** [indulgeIn/YBImageBrowser#39]
就是我传进来的url,可能是YY或者SD存的key,且key不是以https://形式命名的,这个图片已经存在本地中了,这时候就会提示图片下载失败,因为是用SDWebImageDownloader下载的,是不是可以兼容一下呢?

**Comment by indulgeIn** [comment]
最快速的解决方法就是你将图片从缓存中找出来 然后作为本地图片YBImage给图片浏览器

缓存共享问题暂时还没想到一个完美的解决方案

**Comment by ChandHsu** [comment]
![5e03bd33-75c2-41ce-b86b-6fa817753a09](https://user-images.githubusercontent.com/10771362/46204551-2d52c800-c350-11e8-9a67-8d5a7327b30b.png)
我试着修改了一下,这样貌似就不会出现问题了

**Comment by ChandHsu** [comment]
忽略了一个问题,这么做是多余的,因为这个图片已经存在本地了,这时候显示的sourceObject就会携带过来这个图片,也就是说不用触发download,也不要提示"图片下载失败",问题就解决了

**Comment by lijialiang** [comment]
同样遇到这样问题。发现无法通过 `YBImageBrowseCellData` 设置 image

```
- (id<YBImageBrowserCellDataProtocol>)yb_imageBrowserView:(YBImageBrowserView *)imageBrowserView dataForCellAtIndex:(NSUInteger)index {
  YBImageBrowseCellData *data = [YBImageBrowseCellData new];
  data.image // readonly
}
```

**Comment by indulgeIn** [comment]
看一下readme 本地图片用block配置
