### ISSUE TITLE
加载网络图片缩小动画效果不好

### ISSUE THREAD

**Issue by HZRZCW** [indulgeIn/YBImageBrowser#47]
如gif图所示，所加载的网络图片尺寸比例和sourceObject（比如cell的imageView）的尺寸（长宽）比例不一样就会出现这种情况，比例差异越大效果越不好。
![gif](https://user-images.githubusercontent.com/12219811/46645943-e9668b00-cbb9-11e8-9f99-9886581d8484.gif)

**Comment by indulgeIn** [comment]
代码已优化，pods 2.0.5
