### ISSUE TITLE
当图片失效的时候，图片失效的文字复用存在问题

### ISSUE THREAD

**Issue by sherlockmm** [indulgeIn/YBImageBrowser#48]
当图片失效的时候，图片失效的文字复用存在问题
![5110f7837f8947c56f09dda4f91f73db](https://user-images.githubusercontent.com/19612183/46725410-b520c680-ccae-11e8-9814-d6a58d20e5d5.png)

**Comment by indulgeIn** [comment]
代码已修复，pods 2.0.5
