### ISSUE TITLE
希望有个查看原图的功能

### ISSUE THREAD

**Issue by shen0607** [indulgeIn/YBImageBrowser#50]
希望有个查看原图的功能

**Comment by indulgeIn** [comment]
你可以自定义 toolbar 或者 sheetview，添加查看原图按钮，然后自行处理入栈或者模态切换或者重载数据。
一个UI组件不可能面面俱到，若组件集成太多的功能只会给维护带来灾难。所以只能根据自己的业务拓展功能，本组件应该是能灵活拓展的。
