### ISSUE TITLE
运行实例代码，加载高清图片，内存在猛涨，

### ISSUE THREAD

**Issue by chenchizhao** [indulgeIn/YBImageBrowser#51]
我运行你的实例程序,发现内存在猛涨啊，有没有啥优化的方法？
![image](https://user-images.githubusercontent.com/6883210/46900023-268a9000-cece-11e8-8a7c-a2ada4ea9725.png)，然后就闪退了

**Comment by indulgeIn** [comment]
使用代理配置数据源能有效降低内存峰值

**Comment by indulgeIn** [comment]
混合案例是用的数组来配置数据源，这个只是之前为了性能测试，现在我更改了测试用例的数据源，更新了代码以免被误解。

使用数组会持有数据源，绘制过后的图片对象会带来内存负担；使用代理不会持有数据源，数据源会及时释放（当然组件内部有局部缓存机制来提高性能），当然若你的业务代码中持有数据源另说。

**Comment by chenchizhao** [comment]
你说的这测试用例的数据源方法的代码,githu上面有没有更新啊，可以测试一下把？我昨天用你GitHub最新的代码,加载都是1920*1080的分辨率的图片,加载大概70张的时候,就闪退了，我在想,是不是要做一个内存监测机制,监测到内存增长某一个阈值,就进行循环清理

**Comment by indulgeIn** [comment]
我才更新的，如果可能存在潜在的性能问题就用代理配置数据源。

你说的内存检测机制应用价值并不高，在用数组配置数据源的时候，清理内存的方式只有释放掉数据源的 __kindof UIImage 对象，那么图片浏览器回滚的时候需要复位数据，这可能只能利用读写磁盘来实现（类比操作系统进程的内存空间分配），得不偿失。

就像 YYWebImage 和 SDWebImage，它们不会去检测异步解压图片的内存大小，所以若同时下载高清图会内存峰值过高而程序crash。

本组件只是需要你考虑潜在的内存问题，也可能直观的理解为若图片超过 n 张就使用代理否则使用数组，这个 n 暂且可以为 10 ？

**Comment by chenchizhao** [comment]
其实还有一个方法就是内存映射,FastImageCache这里面实现的方法就是采用内存映射的方法，可以解决内存猛涨的问题，
