### ISSUE TITLE
点击关闭的反应时间是不是有点长了

### ISSUE THREAD

**Issue by xiongq** [indulgeIn/YBImageBrowser#54]
iPhone x 12.0.1 测试点击关闭感觉要等0.4s的样子
还有个保存图片，这个没有判断是否有权限

**Comment by indulgeIn** [comment]
这个就是控制器dismiss，肯定比直接视图操作要慢一点，你可以看看其他使用同样方案的app。

权限是判断了的，plist 里面需要你自己去添加权限

**Comment by xiongq** [comment]
谢谢 刚去看源码了
应该有更快的方案
