### ISSUE TITLE
视频播放的处理太简单了。

### ISSUE THREAD

**Issue by LeoAiolia** [indulgeIn/YBImageBrowser#55]
1.播放状态下插拔耳机的处理。

**Comment by LeoAiolia** [comment]
2.播放状态下，进入后台进前台

**Comment by indulgeIn** [comment]
你说的三点需求后面有空了考虑加。

关掉功能不起作用是BUG？代码精简是指哪方面？访问实例变量用不用 self-> 不用纠结是否规范，不同的人或团队有不同的理解；组件内部导入的头文件应该都是有用的，若发现有疏漏麻烦具体指正；if 后面带大括号和换行这个后面会做一下，之前刷算法题成习惯没注意这个问题。
