### ISSUE TITLE
是否是视频的时候隐藏保存按键

### ISSUE THREAD

**Issue by xiongq** [indulgeIn/YBImageBrowser#59]
预览是视频的时候，隐藏保存按键 以及 actionSheet
现在我只能去更改源代码和kvc去隐藏

**Comment by xiongq** [comment]
是否可以是视频的时候自动播放

**Comment by indulgeIn** [comment]
<img width="673" alt="image" src="https://user-images.githubusercontent.com/18362662/47512575-12239b80-d8af-11e8-99b0-72c7d30082bc.png">
多看API
