### ISSUE TITLE
滑动卡顿

### ISSUE THREAD

**Issue by SinglTown** [indulgeIn/YBImageBrowser#60]
稍微大一点的图片(100kb左右),浏览的时候滑动就会卡顿

**Comment by SinglTown** [comment]
我把图片换成.jpg格式,就会好很多了

**Comment by indulgeIn** [comment]
你用的是哪个版本呢，理论上组件的解码压力不会成为性能瓶颈啊

**Comment by SinglTown** [comment]
2.0.1版本

**Comment by SinglTown** [comment]
最新版也这样, png图片就会卡, jpg基本正常

**Comment by indulgeIn** [comment]
你是怎么配置 png 图片数据源的，麻烦贴一下代码

**Comment by indulgeIn** [comment]
新版本地图片的配置是通过一个 imageBlock 闭包，组件会在异步线程处理，应该不会出现访问磁盘 I/O 方面性能问题；如果你的使用没有问题，我猜测可能是 png 的解码造成的卡顿，不过和组件的内存考虑有些冲突。

**Comment by indulgeIn** [comment]
2.0.8 版本  YBImageBrowseCellData 下的 shouldDecodeAsynchronously 类属性，设置为 YES 可以解决。
