### ISSUE TITLE
建议增加图片下载完成的代理回调,以供特定情况下的使用

### ISSUE THREAD

**Issue by ChandHsu** [indulgeIn/YBImageBrowser#62]

**Comment by indulgeIn** [comment]
导入 YBImageBrowseCellData+Internal.h 文件，监听 dataState 属性变化，就能得到一系列的回调。对这个属性的监听是和我对该组件的设计理念有一点冲突的，因为对图片的处理组件内部有很多操作，我并不希望使用者关心和使用它们，这样会有些复杂。为了接口的简洁我不会把这个 dataState 属性暴露在 YBImageBrowseCellData.h 中，所以需要你额外的导入一下内部文件。
