### ISSUE TITLE
点击视频，直接收缩，不是很符合交互习惯

### ISSUE THREAD

**Issue by include11** [indulgeIn/YBImageBrowser#63]
能用这个Demo的，一般都是要做微信、企业微信和钉钉等软件的图和视频混合查看的效果，目前Demo交互和他们有点不一样,Demo的视频这块的交互用起来没那么顺，毕竟那些社交软件的交互是经过用户考验的。

1.未放大的情况下，点击视频，放大视频直接播放，而Demo还要多一步点击播放按钮才能播放
2.从图片滑动到视频的情况下，应该能直接查看视频的总时长，点击播放按钮播放视频，点击非播放按钮的区域隐藏总时长。

**Comment by indulgeIn** [comment]
既然是UI组件，必然不可能满足所有人的需求，视频播放本身是个设计粒度很低的东西，我时间也有限，视频功能做得比较马虎，主要还是图片的处理。所以如果有更高层次的需求，可以考虑自定义。
