### ISSUE TITLE
YBVideoBrowseCellData怎么播放本地路径视频

### ISSUE THREAD

**Issue by smile659974981** [indulgeIn/YBImageBrowser#65]
视频文件路径如下：file:///var/mobile/Containers/Data/Application/BD44519E-CCFB-458B-9329-4A10B1031731/Documents/HyphenateSDK/appdata/13000000001/13100011122/e95d3ae0-de3e-11e8-9377-570c32f6ac4c.mp4，谢谢

**Comment by sujiewen** [comment]
直接可以播放的
YBVideoBrowseCellData *imgData = [YBVideoBrowseCellData new];
            imgData.url = [NSURL fileURLWithPath:responseObject];
            imgData.sourceObject = message.view;
            imgData.autoPlayCount = 1;
            YBImageBrowser *browser = [YBImageBrowser new];
            browser.dataSourceArray = @[imgData];
            [browser show];

**Comment by indulgeIn** [comment]
嗯，直接读取本地视频文件，传给 YBVideoBrowseCellData 的 url、phAsset 或 avAsset 都行

**Comment by liujieyuu** [comment]
我的本地视频文件地址是file:///private/var/mobile/Containers/Data/Application/8AD8798F-AC7C-43EA-BA34-E154D1F788E1/tmp/myMovie.mov
执行代码：
            YBImageBrowseCellData *data = [YBImageBrowseCellData new];
            data.url = self.videoURL;
//          PhotoOrVedioCollectionViewCell *cell = (PhotoOrVedioCollectionViewCell*)[collectionView cellForItemAtIndexPath:indexPath];
            data.sourceObject = self.view;
            [browserDataArr addObject:data];
          YBImageBrowser *browser = [YBImageBrowser new];
        browser.dataSourceArray = @[data];
        browser.currentIndex = 0;
        [browser show];
提示图片下载失败  @indulgeIn
