### ISSUE TITLE
视屏拖动进度条界面卡住但还有声音

### ISSUE THREAD

**Issue by chglog** [indulgeIn/YBImageBrowser#67]
当加载网络视屏时，当视屏时间稍微大点的时候  拖动滚动条时   界面卡住（应该是在加载，如果是的话应该要有个提示） 但是声音却还在正常播放（应该提示正在加载，并且关闭声音）  不知道我说的是否正确    望作者指导

**Comment by indulgeIn** [comment]
这些属于业务需求问题，我只是做了一个简单的播放器方便简易使用，如果你的项目中有更多要求，建议自己写一个吧
