### ISSUE TITLE
选择系统相册一张图,iOS11之前无法获取PHAsset 对象问题

### ISSUE THREAD

**Issue by YanLYM** [indulgeIn/YBImageBrowser#69]
![image](https://user-images.githubusercontent.com/28438058/48041534-8ff17c00-e1b8-11e8-9ec2-697674396f28.png)

选择了系统相册中的一张图,设置给UIImageView,点击图片需要用这个框架预览,但是这个方法这里iOS11之后才可以PHAsset *asset对象,iOS11之前拿不到,导致图片浏览YBImageBrowseCellData对象无法设置phAsset, 这个问题要怎么处理

**Comment by indulgeIn** [comment]
使用 imageBlock 属性直接设置 UIImage 实例
