### ISSUE TITLE
YBImageBrowser 和UIMenuController有冲突？

### ISSUE THREAD

**Issue by sujiewen** [indulgeIn/YBImageBrowser#72]
YBImageBrowser 和UIMenuController有冲突？显示YBImageBrowser，UIMenuController响应的菜单点击事件无法响应，只要打开YBImageBrowser就存在问题

**Comment by indulgeIn** [comment]
组件的windowLevel是UIWindowLevelStatusBar + 1，为什么图片浏览器展示的时候还会有 UIMenuController ？

**Comment by sujiewen** [comment]
没人碰到这个问题吗

**Comment by indulgeIn** [comment]
YBImageBrowser 的 shouldHideStatusBar 属性置为 NO

**Comment by indulgeIn** [comment]
YBImageBrowser 的 shouldHideStatusBar 属性置为 NO，只能暂时去掉隐藏导航栏的功能了。
