### ISSUE TITLE
能支持自己传图片和视频的原始frame进来吗?

### ISSUE THREAD

**Issue by lipeiaiwo** [indulgeIn/YBImageBrowser#73]
能支持自己传图片和视频的原始frame进来吗? 有些场景没办法给父视图,只能自己计算图片的frame.
现在做的Im聊天功能,一个图片一个cell,多图的时候不好处理.

**Comment by indulgeIn** [comment]
如果获取不了视图对象，那么是不是可以理解为没有绘制到屏幕上，所以这个用于动画的参数就没必要传了。
