### ISSUE TITLE
感谢博主，为何我的九宫格点击图片放大之后就全黑了，并没有显示图片？怎么破

### ISSUE THREAD

**Issue by ios52013** [indulgeIn/YBImageBrowser#78]

**Comment by indulgeIn** [comment]
应该是数据源没搞对，看看demo吧

**Comment by ios52013** [comment]
我都是直接把你的demo里面的代码copy过来了，而且我打了断点，看了数据源的和你的demo也是同一个对象

**Comment by ios52013** [comment]
in大佬，就没有其他小伙伴遇到这个梗么

**Comment by ios52013** [comment]
方便加你QQ或者微信吗？in大佬

**Comment by ios52013** [comment]
波哥介意帮忙看看吗？我的代码如下：

#import "ViewController.h"
#import "YBImageBrowser.h"



@interface ViewController ()<YBImageBrowserDataSource>

/**
 图片名的数组
 */
@property (nonatomic, strong)NSMutableArray *imageArr;

/**
 图片对象的数组 作为数据源
 */
@property (nonatomic, strong)NSMutableArray *dataArr;
@end

@implementation ViewController

///系统自带
- (void)viewDidLoad {
    [super viewDidLoad];
    //
    self.dataArr = [NSMutableArray array];
    //
    [self createImageView];
}

///创建九宫格ImageView
-(void)createImageView{
    
    CGFloat width = ([UIScreen mainScreen].bounds.size.width -20*2 -10*2)/3;
    CGFloat height = 100;
    for (NSInteger i = 0; i<self.imageArr.count; i++) {
        UIImage *image = [UIImage imageNamed:self.imageArr[i]];
        UIImageView *button = [[UIImageView alloc] initWithFrame:CGRectMake(i%3 * (width+10), i/3 *(height+10), width, height)];
        button.userInteractionEnabled = YES;
        button.tag = i;
        button.backgroundColor = [UIColor redColor];
        button.image = image;
        
        //添加收拾
        UITapGestureRecognizer *tap = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(imageOnClick:)];
        [button addGestureRecognizer:tap];
        
        [self.view addSubview:button];
        
        [self.dataArr addObject:button];
    }
}


#pragma mark ------ 图片呗点击 ------------
-(void)imageOnClick:(UIGestureRecognizer *)tapGR{
    NSLog(@"------%ld-------",tapGR.view.tag);
    [self showBrowserForMixedCaseWithIndex:tapGR.view.tag];
}


- (void)showBrowserForMixedCaseWithIndex:(NSInteger)index {
    // 设置数据源代理并展示
    YBImageBrowser *browser = [YBImageBrowser new];
    browser.dataSource = self;
    browser.currentIndex = index;
    [browser show];
    
}

// 实现 <YBImageBrowserDataSource> 协议方法配置数据源
- (NSUInteger)yb_numberOfCellForImageBrowserView:(YBImageBrowserView *)imageBrowserView {
    return self.imageArr.count;
}
- (id<YBImageBrowserCellDataProtocol>)yb_imageBrowserView:(YBImageBrowserView *)imageBrowserView dataForCellAtIndex:(NSUInteger)index {
    YBImageBrowseCellData *data = [YBImageBrowseCellData new];
    
    data.imageBlock = ^__kindof UIImage * _Nullable{
        //
        return [UIImage imageNamed:self.imageArr[index]];
    };
    
    data.sourceObject = [self sourceObjAtIdx:index];
    return data;
}


-(id)sourceObjAtIdx:(NSInteger) indx{
    UIImageView *iv = self.dataArr[indx];
    return iv;
}

#pragma mark ------ LAZY ------------
-(NSMutableArray *)imageArr{
    if (!_imageArr) {
        _imageArr = [NSMutableArray array];
        NSArray *arr = @[@"1",@"2",@"3",@"4"];
        _imageArr = [arr mutableCopy];
    }
    
    return _imageArr;
}

**Comment by indulgeIn** [comment]
看起来问题是这个 return [UIImage imageNamed:self.imageArr[index]]; 没有返回有效的图片吧

**Comment by indulgeIn** [comment]
看起来问题是这个 return [UIImage imageNamed:self.imageArr[index]]; 没有返回有效的图片吧。
别打断点在这里，你格外写代码读取图片，看能不能读得到

**Comment by ios52013** [comment]
- (id<YBImageBrowserCellDataProtocol>)yb_imageBrowserView:(YBImageBrowserView *)imageBrowserView dataForCellAtIndex:(NSUInteger)index {
    YBImageBrowseCellData *data = [YBImageBrowseCellData new];
    
    data.imageBlock = ^__kindof UIImage * _Nullable{
        //
        
        return [YBImage imageNamed:self.imageArr[index]];
    };
    
    data.sourceObject = [self sourceObjAtIdx:index];
    
    UIImage *img = data.image;
    
    return data;
}

波哥，请问您这个block是不是给data的image属性赋值？也就是我是否可以通过data的image属性获取到这图片？我在这里读取到的img的确是空nil。

**Comment by ios52013** [comment]
但是我通过block 是可以拿到图片对象的，UIImage *img = data.imageBlock();这样是有图的

**Comment by indulgeIn** [comment]
排查一下吧，demo能跑应该不是组件代码逻辑的问题
