### ISSUE TITLE
手势bug

### ISSUE THREAD

**Issue by yinxianwu** [indulgeIn/YBImageBrowser#79]
预览模式的时候，往下拉一点点 出现缩小一点点动画 然后立马放手
会先恢复原大小，再消失

**Comment by ChuGuangFu** [comment]
同样的问题，打了下断点发现是在恢复原来大小后又响应了单击的手势事件所以会消失，建议增加以下判断在拖拽手势失败的情况下再响应单击手势的事件
[tapSingle requireGestureRecognizerToFail:pan];

**Comment by indulgeIn** [comment]
2.2.0 更新了。
已修复问题
