### ISSUE TITLE
希望自定义右上角的功能按钮的方式更灵活

### ISSUE THREAD

**Issue by lqcjdx** [indulgeIn/YBImageBrowser#8]
现在有个问题，假如我右上角要展示一个删除的按钮（我要的是删除按钮），那么很难实现这种功能，在fuctionDataArray.count==1并且ID=YBImageBrowserFunctionModel_ID_savePictureToAlbum时是保存功能，只能实现图标的更换，不能实现功能的更换。
我觉得应该修改一下下面的实现：
- (void)yBImageBrowserToolBar:(YBImageBrowserToolBar *)imageBrowserToolBar didClickRightButton:(UIButton *)button {
    if (!self.fuctionDataArray.count) return;
    if (self.fuctionDataArray.count == 1 && [self.fuctionDataArray[0].ID isEqualToString:YBImageBrowserFunctionModel_ID_savePictureToAlbum]) {
        //直接保存图片
        [self savePhotoToAlbumWithCurrentIndex];
    } else {
        //弹出功能栏
        if (_functionBar) {
            [_functionBar show];
        }
    }
}

应该在count==1并且![self.fuctionDataArray[0].ID isEqualToString:YBImageBrowserFunctionModel_ID_savePictureToAlbum]时应该给一个方便的回调方法，或者通过代理的方式询问用户是否要自定义这个按钮点击事件。

我想这种需求（只想在右上角自定义一个功能按钮，而不是非要通过类似actionsheet的方式弹出超过一个的功能列表）还是蛮大的，望优化。

另外这个actionBar弹出来的页面没有适配iPhone X。

**Comment by indulgeIn** [comment]
同时我优化了点击功能选项的代理回调事件，可以更方便的拿到当前显示图片的model

**Comment by lqcjdx** [comment]
@indulgeIn 期待尽快更新！

**Comment by lqcjdx** [comment]
@indulgeIn 不好意思，我发现有两种方式可以拿到右上角的点击事件回调，如果其他朋友需要的话也可以参考：

1.修改toolBar的代理从browser指向self
browser.toolBar.delegate = nil;
browser.toolBar.delegate = self;
然后self中实现代理方法：
- (void)yBImageBrowserToolBar:(YBImageBrowserToolBar *)imageBrowserToolBar didClickRightButton:(UIButton *)button
{
    //do something
}

2.修改toolBar.rightBtn的target
UIButton *rightBtn = browser.toolBar.rightButton;
for(id target in rightBtn.allTargets){
       [rightBtn removeTarget:target action:nil forControlEvents:UIControlEventTouchUpInside];
}
[rightBtn addTarget:self action:@selector(rightBtnClick:) forControlEvents:UIControlEventTouchUpInside];

**Comment by indulgeIn** [comment]
@lqcjdx 最近有点忙，昨天晚上才更新pods
