### ISSUE TITLE
自动播放

### ISSUE THREAD

**Issue by xiongq** [indulgeIn/YBImageBrowser#83]
autoPlayCount = 1
部分视频不能自动播放

**Comment by ApesTalk** [comment]
@xiongq 你解决了吗？我这里浏览系统相册里的视频，不能实现自动播放：

操作流程：设置data.autoPlayCount = 1，选中demo的“系统相册”tab ，点击一个视频。

- (void)showBrowserForSystemAlbumWithIndex:(NSInteger)index {
    YBImageBrowser *browser = [YBImageBrowser new];
    browser.dataSource = self;
    browser.currentIndex = index;
    [browser show];
}

// <YBImageBrowserDataSource>

- (NSUInteger)yb_numberOfCellForImageBrowserView:(YBImageBrowserView *)imageBrowserView {
    return self.dataArray.count;
}

- (id<YBImageBrowserCellDataProtocol>)yb_imageBrowserView:(YBImageBrowserView *)imageBrowserView dataForCellAtIndex:(NSUInteger)index {
    PHAsset *asset = (PHAsset *)self.dataArray[index];
    if (asset.mediaType == PHAssetMediaTypeVideo) {
        
        // Type 1 : 系统相册的视频 / Video of system album
        YBVideoBrowseCellData *data = [YBVideoBrowseCellData new];
        data.autoPlayCount = 1;
        data.phAsset = asset;
        data.sourceObject = [self sourceObjAtIdx:index];

        return data;
    } else if (asset.mediaType == PHAssetMediaTypeImage) {
        
        // Type 2 : 系统相册的图片 / Image of system album
        YBImageBrowseCellData *data = [YBImageBrowseCellData new];
        data.phAsset = asset;
        data.sourceObject = [self sourceObjAtIdx:index];

        return data;
    }
    return nil;
}
