### ISSUE TITLE
感谢作者，提个问题放到cell里的话，点击图片打开大图没动画，缩小时就有动画

### ISSUE THREAD

**Issue by 877209649** [indulgeIn/YBImageBrowser#84]
感谢作者，提个问题放到cell里的话，点击图片打开大图没动画，缩小时就有动画

**Comment by 877209649** [comment]
谢谢你的回复。
是的，我的是放在cell 里的九宫格imageView，将sourceView设置为点击的UIImageView，没有入场动画。

**Comment by indulgeIn** [comment]
需要检查这个sourceobject的正确性 参照demo吧

**Comment by 877209649** [comment]
好的，谢谢。

**Comment by indulgeIn** [comment]
问题解决了么
