### ISSUE TITLE
关于网络图片url问题

### ISSUE THREAD

**Issue by TML007** [indulgeIn/YBImageBrowser#95]
这种网络图片URL：https://qnwww2.autoimg.cn/youchuang/g29/M01/D4/33/autohomecar__ChsEflwXbfOAfQtdAACqqmgic_M952.png?imageView2/3/w/640|watermark/2/text/6KGM5ZyG5rG96L2m5aSn5YWoDQrmsb3ovabkuYvlrrY=/font/5b6u6L2v6ZuF6buR/fontsize/350/fill/d2hpdGU=/dissolve/100/gravity/SouthEast/dx/5/dy/5   用在您demo上图片无效

**Comment by indulgeIn** [comment]
.png后面为什么还有这么长字符串，你这是markdown里面复制的么

**Comment by TML007** [comment]
> .png后面为什么还有这么长字符串，你这是markdown里面复制的么

是抓汽车之家app的数据

**Comment by indulgeIn** [comment]
嗯 这个路径明显是需要额外处理的 所以浏览器能显示出来 app里面是不行的
