### ISSUE TITLE
父类为UIStackview 显示异常

### ISSUE THREAD

**Issue by tryEvething** [indulgeIn/YBImageBrowser#97]
![a](https://user-images.githubusercontent.com/18730979/50211545-d9d2a200-03b3-11e9-903f-cfc4ed07bc4c.gif)

**Comment by indulgeIn** [comment]
哪里异常了没太看明白？

**Comment by tryEvething** [comment]
UIStackview装着5个UIImageView,当弹出的时候,当前这个ImageView会消失,然后退出浏览时,这个图片会重新加载到UIStackview上

**Comment by indulgeIn** [comment]
autoHideSourceObject 可以取消这个功能
