### ISSUE TITLE
手势会让自定义toolbar 隐藏。。。但并没有可以设置手势不隐藏toolbar的地方

### ISSUE THREAD

**Issue by JessieWu0921** [indulgeIn/YBImageBrowser#98]
不能自由控制toolbar的显示和隐藏……

**Comment by JessieWu0921** [comment]
如果不是push进入的。。。就很尴尬。。。pansignle就会直接调dismiss。。。hidden掉toolbar

**Comment by indulgeIn** [comment]
YBImageBrowserToolBarProtocol 有个 - (void)yb_browserPageIndexChanged:(NSUInteger)pageIndex totalPage:(NSUInteger)totalPage data:(id<YBImageBrowserCellDataProtocol>)data; 方法，应该就能控制了吧
